### ISSUE TITLE
Update instructions to debug java worker

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#100]
Debugging instructions are not clear in the [devdoc.md](https://github.com/Azure/azure-functions-java-worker/blob/dev/azure-functions-java-worker/devdoc.md)

**Comment by pragnagopa** [comment]
@JunyiYi - I am trying to follow the dev doc to setup step by step debugging with latest host. Instructions are not very clear as I am new to Java. Can you please update the devdoc to include links/steps on how debug?

**Comment by JunyiYi** [comment]
@pragnagopa , if you are using IntelliJ, I believe you can attach to the Java process by using the "Debug" -> "Attach to Local Process..." menu item.

**Comment by pragnagopa** [comment]
Given that communication between host and language worker would break for multiple reasons, it would help to have clear instructions on setting up debugging.  Can you please update the dev doc with more details? For example, i think you need to set the debug port via environment variable worker:java:debug

**Comment by asavaritayal** [comment]
Pragna updated the README.
