### ISSUE TITLE
allow function specific lib directories; classpath fails due to if-else

### ISSUE THREAD

**Issue by aappddeevv** [Azure/azure-functions-java-worker#117]
Currently, a common lib directory is used across all functions in a functionapp. It would be good to allow a function specific lib directory to be on the classpath (good to have), or at least the ability set the classpath in config somehow (preferred).

A set of functions may use different jar versions for different functions due to dependency requirements. In fact, I'm not sure that the following code is correct around the if statement (in the FunctionMethodDescriptor class):
```java
 * Gets the function method's parent directory where each function method should be residing (1-level up)
     */
    public File getParentDirectory() {
        if (this.parentDirectory == null) {
            // the conventions are:
            // 1. jar in the function's method folder or
            // 2. in the function method's parent folder where all the method directories are children

            if (isJarInMethodFolder()) { 
                this.parentDirectory = getJarDirectory().getAbsoluteFile().getParentFile(); //up one level
            }
            this.parentDirectory = this.jarDirectory.getAbsoluteFile(); // otherwise convention #2
        }
        return this.parentDirectory;
    }
```
I think it is missing an else clause. That's probably why when you place your jar in the function dir and have jars in (root/lib or ../lib relative to the function dir), method execution fails.

All of this forces you into a fatjar per function if you have functions with dependencies inconsistent with other java functions in your functionapp.

Perhaps removing all the defaulting behavior here except that all jars in the function dir are on the classpath *and* you can specify other classpaths via function.json.

**Comment by kaibocai** [comment]
This is already the default behavior in azure function v4.
