### ISSUE TITLE
@BlobTrigger(name = "content", path = "container/{name}", dataType = "Stream") ? content

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-functions-java-worker#119]
[Document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-java#data-types) doesn't mention Data Type `Stream`, but I found this [DataType](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Description/Binding/DataType.cs).

If set dataType to irrelevant type, error message mentions 
    
    Error converting value "xxx" to type 'System.Nullable`1[Microsoft.Azure.WebJobs.Script.Description.DataType]'. 

Try to set dataType="Stream" and find corresponding java class, no progress. Only get error `System.Private.CoreLib: Stream does not support writing`.

So is dataType="Stream" usable, if so, which java class is matched?

**Comment by JunyiYi** [comment]
Unfortunately `Stream` is not supported for now.
