### ISSUE TITLE
Add support for Java 11

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#120]
Java 11 will be the next version with LTS(long term support) http://www.oracle.com/technetwork/java/javase/eol-135779.html

**Comment by Clockwork-Muse** [comment]
Also plugging this for my own issue #60 because it's necessary for future support of full async support.

**Comment by nicenemo** [comment]
Any ideas yet on Java 11 and Java 12 support?

**Comment by SoucianceEqdamRashti** [comment]
When will java 11/12 be available for azure functions?

**Comment by pragnagopa** [comment]
cc @FabianMeiswinkel

**Comment by ericwyles** [comment]
Hi, any update for java 11 support? I'm running on to the same ClassCastException running Maven target referenced in #14927

Java 11 is LTS and has been out for a while, was curious if anyone is actively working on updating.

Thanks

**Comment by md42** [comment]
Any updates on this? A public java roadmap would be nice and would help to get java folks on functions. Java 8 kind of gets out of fashion ;)

**Comment by mnriem** [comment]
For changes on the Java side, see PR https://github.com/Azure/azure-functions-java-worker/pull/347

**Comment by jabrena** [comment]
Any progress on it?

**Comment by pragnagopa** [comment]
tagging -  @kulkarnisonia16 / @anirudhgarg / @amamounelsayed  for an ETA

**Comment by evenh** [comment]
Java 8 is EOL and has been for some time. I hope Microsoft soon will realize that it’s pretty embarrassing to not have have support for the current LTS version that has been around since September 2018.

**Comment by anirudhgarg** [comment]
I can confirm that we have started working on Java 11 support and we are hoping for a preview in the next few months.

**Comment by amamounelsayed** [comment]
https://azure.microsoft.com/en-us/updates/java-11-for-azure-functions-is-now-available-in-preview/

**Comment by EwanNoble** [comment]
The docs are showing the preview version of Java 11 supporting V3 Functions only, are you able to confirm whether it will be coming to V2 as well?

**Comment by mnriem** [comment]
Great work!

**Comment by amamounelsayed** [comment]
@EwanNoble Thank you so much for your message. There is no plan currently to support V2.

**Comment by pragnagopa** [comment]
@EwanNoble  - Please https://github.com/Azure/app-service-announcements/issues/266 . We encourage upgrading to V3 as soon as you can. Thanks.

**Comment by pragnagopa** [comment]
Closing as the feature is now preview.
