### ISSUE TITLE
Event Hubs trigger doesn't support batch trigger

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-java-worker#122]
The best practice for running functions at high scale is to pull in a batch of messages in a single execution (`EventData[]`).  For javascript this is described in the function.json as:

```json
{
...
"cardinality": "many"
}
```

1. The Java attribute should allow for a configurable flag to set cardinality to many
  * The generated function.json should include `"cardinality": "many"`
1. The host should be able to send and have serialized `EventData[]` to the Java worker

@asavaritayal @pragnagopa as FYI

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-functions-java-library#14
