### ISSUE TITLE
Unable to build functions locally with runtime 2.0.11933

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#148]
Functions fail to build locally with Azure Function CLI v 2.0.1-beta.32

**Comment by pragnagopa** [comment]
@TurtleBeach - investigating this issue. Runtime 2.0.11933 should not require any code changes to run locally or on Azure.

**Comment by pragnagopa** [comment]
cc: @jdneo 
@TurtleBeach - I cannot repro this issue. Created function app using:

```
mvn archetype:generate -DarchetypeGroupId=com.microsoft.azure -DarchetypeArtifactId=azure-functions-archetype 
```
Here is my snippet from pom.xml
```
<azure.functions.maven.plugin.version>1.0.0-beta-2</azure.functions.maven.plugin.version>
<azure.functions.java.library.version>1.0.0-beta-4</azure.functions.java.library.version>
```
My best guess on why you are seeing this issue is, you might have cached azure.functions.java.library in local maven repo. In windows, delete
```
C:\Users\username\.m2\repository\com\microsoft\azure\azure-functions*
```

**Comment by TurtleBeach** [comment]
@pragnagopa I deleted all azure-functions* folders in maven repository, and reverted to the two maven and java library versions you referenced above. The function now builds, and will run (locally) up to the point of a "createResponse()" call, at which time it hangs (throws some kind of internal exception in then stays in a tight loop). This is symptomatic of a method missing from the library - and is what led us down the garden path last week trying to get a working function using 2.0.11933. What has worked locally for me was using maven plugin beta-3 and functions library beta-5 (along with the sona... reference in POM that you provided last week) - HOWEVER that then required changing source to use the createResponseBuilder() method, and the attendant problems with enum parameter. For this current testing I painstakingly modified source yet again to revert to the old syntax.
I concede it is a local library problem, but I am at a loss to know where to get the right library (this testing ended 5 minutes ago, so presumably there has not been an update to beta-2 or beta-4 versions in that time.

**Comment by ahmelsayed** [comment]
I just pushed `beta.33` with a fix for this

**Comment by TurtleBeach** [comment]
That works locally. Thanks. I will test deployment, but presumably will not be an issue.

**Comment by TurtleBeach** [comment]
Deployment also works - but not reading APP SETTINGS using System.getProperty("xc"). (in Java function)

**Comment by pragnagopa** [comment]
CLI release beta.33 fixed the issue.
