### ISSUE TITLE
Java JVM updates for Azure Functions

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#149]
Tracking item to figure out JVM updates for functions (App Service).

Users should be able to turn on/ off java runtime updates.

**Comment by pragnagopa** [comment]
cc: @selvasingh , @asavaritayal

**Comment by pragnagopa** [comment]
Starting with [functions runtime v2.0.11961-alpha](https://github.com/Azure/azure-functions-host/releases/tag/v2.0.11961-alpha) , users can configure path to java.exe by specifying an appsetting 

| APP SETTING NAME  | VALUE |
| ------------- | ------------- |
| languageWorkers:java:defaultExecutablePath   | ../../../../Home/Site/Tools/bin/java  |   

**Note**: value is relative to JAVA_HOME path

**Comment by pragnagopa** [comment]
Fix https://github.com/Azure/azure-functions-host/pull/3233 supports specifying full path  for languageWorkers:java:defaultExecutablePath

**Comment by asavaritayal** [comment]
App Service Team is going to start pushing updates quarterly.
