### ISSUE TITLE
@CosmosDBOutput binding does not work for java functions

### ISSUE THREAD

**Issue by ruyakubu** [Azure/azure-functions-java-worker#153]
The Azure Functions output bindings annotation template for Cosmo DB does not work for java.  When a user tries to store json data to Cosmos DB using @CosmosDBOutput, nothing happens. However, if the user adds the cosmos db dependency class in the pom.xml, then explicitly connects and stores the same json data to a Cosmos DB instance, the data is successfully saved in the database.

It looks like @CosmosDBOutput is not able to connect to Cosmos DB given the database name, collection name and connection string.

--------------------------------
Here's the local.settings.json:
---------------------------------
{

  "IsEncrypted": false,

  "Values": {

    "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;AccountName=<value>;AccountKey=<value>;EndpointSuffix=core.windows.net",

    "AzureWebJobsDashboard": "<Storage Account Connection String>",

    "DbConnectionString":"AccountEndpoint=https://users.documents.azure.com:443/;AccountKey=<value>;"

  }

}

------------------------------------
Here's the source code:
-----------------------------------
package com.demo.functions;

import java.util.LinkedHashMap;

import com.microsoft.azure.serverless.functions.annotation.*;
import com.microsoft.azure.serverless.functions.annotation.CosmosDBOutput;
//import com.microsoft.azure.documentdb.Document;
import com.microsoft.azure.serverless.functions.*;
import com.microsoft.azure.serverless.functions.OutputBinding;

import com.demo.functions.VisionService;

public class EventBlob {
    /**
     * This function will be invoked when a new or updated blob is detected at the specified path. The blob contents are provided as input to this function.
     */
    @FunctionName("EventBlob")
    @StorageAccount("AzureWebJobsStorage")
    public void blobHandler(
        @BlobTrigger(name = "content", path = "iotblobdata/{name}", dataType = "binary") byte[] content,
        @BindingName("name") String name,
    @CosmosDBOutput(name = "outputDocument", databaseName = "users", collectionName = "profiles", connectionStringSetting = "CosmosDbConnection") OutputBinding<String> outputDocument,
        final ExecutionContext context
    ) {
    	
        VisionService vs = new VisionService();
        String jsonData = vs.analyzeImage(name, content);
        
        
      	context.getLogger().info("Document: \n" + jsonData);
        outputDocument.setValue(jsonData);
        
    }
}

**Comment by pragnagopa** [comment]
@jeffhollan - can you please verify if this reproes with latest bits?

**Comment by ruyakubu** [comment]
Was able to validate that this has been resolved in release version 2.  The blobTrigger output data is successfully stored in a CosmosDB database.

- Works in Local Azure Function runtime

- When function is deployed on Azure, works when user sets the DB connect string in the functions "Application Setting" configuration section.
