### ISSUE TITLE
BlobTrigger Function timesout after it completes executing a java function.

### ISSUE THREAD

**Issue by ruyakubu** [Azure/azure-functions-java-worker#154]
Blob Triggered function throws a TimeOut error after it completes executing the java function.  The functionality for the azure function is short and straight forward.  It executes successfully in the Local environment.  However, it TimesOut when deployed to Azure.

####Azure App Insights - Invocation Log Details:

Executing  'Functions.Analyze' (Reason='New blob detected:  iotblobdata/labrador-puppy.jpg',  Id=543fd2bc-2db7-4597-86ba-270023ef559b) | Information
-- | --
Java Blob trigger function processed a blob. Name: labrador-puppy.jpg   Size: 17404 Bytes | Information
Is image considered racy Adult content? %s false | Information
Racy Adult content confidence score: %s 0.011185577139258385 | Information
Timeout  value of 00:05:00 exceeded by function 'Functions.Analyze' (Id:  '543fd2bc-2db7-4597-86ba-270023ef559b'). Initiating cancellation. | Error
Microsoft.Azure.WebJobs.Host: Timeout value of 00:05:00 was exceeded by function: Functions.Analyze. | Error
Executed 'Functions.Analyze' (Failed, Id=543fd2bc-2db7-4597-86ba-270023ef559b) | Error

#### Investigative information

-------------------------------
Here's the source code:
-------------------------------

/**
 * Azure Functions with Azure Blob trigger.
 */
public class Analyze {
	
	 public static String apiKey = "<key-value>";
	
    /**
     * This function will be invoked when a new or updated blob is detected at the specified path. The blob contents are provided as input to this function.
     */
    @FunctionName("Analyze")
    @StorageAccount("AzureWebJobsStorage")
    public void blobHandler(
        @BlobTrigger(name = "content", path = "iotblobdata/{name}", dataType = "binary") byte[] content,
        @BindingName("name") String name,
        final ExecutionContext context
    ) {
        context.getLogger().info("Java Blob trigger function processed a blob. Name: " + name + "\n  Size: " + content.length + " Bytes");
               
        // invoke cognitive service to analyze image
        ComputerVisionAPIImpl client = Analyze.getClient(apiKey);
        client.withAzureRegion(AzureRegions.WESTUS);
        List<VisualFeatureTypes> visualFeatureTypes = new ArrayList<VisualFeatureTypes>();
        visualFeatureTypes.add(VisualFeatureTypes.FACES);
        visualFeatureTypes.add(VisualFeatureTypes.ADULT);

        ImageAnalysisInner result = client.analyzeImageInStream(
                content,
                visualFeatureTypes,
                null,
                null);

        JSONObject document = new JSONObject();
        document.put("id", java.util.UUID.randomUUID());

        if(result.adult() != null &&
                result.adult() != null) {
            context.getLogger().info("Is image considered racy Adult content? %s\n" +  result.adult().isRacyContent());
            context.getLogger().info("Racy Adult content confidence score: %s\n" +  result.adult().racyScore() );
            

            document.put("adult", result.adult().toString());
        }

        
    }
    
    public static ComputerVisionAPIImpl getClient(final String subscriptionKey) {
        return new ComputerVisionAPIImpl(
                "https://westus.api.cognitive.microsoft.com/vision/v1.0/",
                new ServiceClientCredentials() {
                    @Override
                    public void applyCredentialsFilter(OkHttpClient.Builder builder) {
                        builder.addNetworkInterceptor(
                                new Interceptor() {
                                    @Override
                                    public Response intercept(Interceptor.Chain chain) throws IOException {
                                        Request request = null;
                                        Request original = chain.request();
                                        // Request customization: add request headers
                                        Request.Builder requestBuilder = original.newBuilder()
                                                .addHeader("Ocp-Apim-Subscription-Key", subscriptionKey);
                                        request = requestBuilder.build();
                                        return chain.proceed(request);
                                    }
                                });
                    }
                });
    }
}

**Comment by asavaritayal** [comment]
@ruyakubu can you please confirm if you're still seeing this error with the latest bits in prod? so we can investigate further.

**Comment by ruyakubu** [comment]
Was able to validate that this has been resolved in release version 2.
