### ISSUE TITLE
Cleanup Overload Resolver

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#155]
Java worker still has left over code from an early prototype before annotations were defined as  Java worker needed a list of well known binding types to parse the function.json

https://github.com/Azure/azure-functions-java-worker/blob/0f83664f355d196654d7c67b00469302b0a8eeed/src/main/java/com/microsoft/azure/functions/worker/binding/BindingDefinition.java#L17

Need to clean up [OverloadResolver.java](https://github.com/Azure/azure-functions-java-worker/blob/0f83664f355d196654d7c67b00469302b0a8eeed/src/main/java/com/microsoft/azure/functions/worker/broker/OverloadResolver.java) to only allow functions defined using annotations

**Comment by asavaritayal** [comment]
FYI this impact auto-generated annotation reference

**Comment by pragnagopa** [comment]
Deleted BindingType in https://github.com/Azure/azure-functions-java-worker/commit/3f3f967365b7a312f4ba90feb604da6fe38fb226
