### ISSUE TITLE
HttpResponseMessage set headers and "raw" flag

### ISSUE THREAD

**Issue by bbilger** [Azure/azure-functions-java-worker#16]
Hi,
Is there any way to specify headers and "raw" flag on a `HttpResponseMessage`?

something like this: https://github.com/Azure/azure-webjobs-sdk-script/issues/942#issuecomment-263358417

It seems like the only way to create a `HttpResponseMessage` is through `HttpRequestMessage#createResponse` which doesn't allow me to set headers and the raw flag; or is there any other way to do this?

**Comment by JunyiYi** [comment]
Definitely it will be supported in the near future (probably in three weeks). And a strongly typed HttpRequestMessage<T> and HttpResponseMessage<T> is being developed.

**Comment by JunyiYi** [comment]
Add support of `addHeader(String, String)` and `getHeader(String)` for `HttpResponseMessage<T>` in #20 . It may take ~3 weeks to deploy the changes to Azure.

`isRaw` will not be supported. Azure team are planning to remove it from Node as well.

**Comment by bbilger** [comment]
@JunyiYi 
Thanks!
Will there, however, be any replacement for "isRaw"? I mean there are valid use cases for this.

**Comment by nicenemo** [comment]
What is the motivation for removal? and indeed alternatives?

**Comment by JunyiYi** [comment]
Fixed with BETA-2. Please update both Azure CLI runtime as well as Azure Functions Java core package version.

**Comment by bbilger** [comment]
Hi @JunyiYi ,
Thanks so far but if I don't get the point about `isRaw`. How can I return a string left untouched (or ideally a byte array without getting base64 encoded)?

```java
@FunctionName("hello")
public HttpResponseMessage<String> hello(@HttpTrigger(name = "req", methods = {"get", "post"}, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<String> req, ExecutionContext context) {
	context.getLogger().info("started");
	context.getLogger().info(req.getBody());
	HttpResponseMessage<String> response = req.createResponse(200, "{\"test\": \"test\"}");
	response.addHeader("Content-Type", "application/json");
	return response;
}
```

`curl -v -H "Accept: application/json" http://localhost:7071/api/hello`
returns `"{\"test\": \"test\"}"` instead of `{"test": "test"}`

`curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:7071/api/hello`
logs (looks like it was de-serialized and re-serialized)
```
{
  "key1": "value1",
  "key2": "value2"
}
```

`curl -d '{"broken' -H "Content-Type: application/json" -X POST http://localhost:7071/api/hello`
crashes (which kind of proves that's it's not passed as is)
