### ISSUE TITLE
@CosmosDBTrigger does not convert input data to POJO

### ISSUE THREAD

**Issue by dsyer** [Azure/azure-functions-java-worker#160]
If I have a handler method with a `@CosmosDBTrigger(...) List<Foo> foos` I would expect that the incoming list would be of `Foo`, but actually it comes in as `LinkedHashMap`, causing a class cast exception downstream. I recognize this as the default behaviour of Jackson if you ask for a `List` and don't specify the element type, but the element type is known to Azure, so it should be able to do the conversion.

**Comment by pragnagopa** [comment]
This is by design. As of now, we only support basic data types defined in [TypedData](https://github.com/Azure/azure-functions-language-worker-protobuf/blob/dev/src/proto/FunctionRpc.proto#L281).  We are yet to design a system that can support strong/rich types.

**Comment by dsyer** [comment]
I don't think it's anything to do with the protobufs. The protobuf transports raw data, and this is converted to Java objects by the worker. It can convert to `Foo` but not `List<Foo>` - it just isn't inspecting the method signature in the right way.

**Comment by pragnagopa** [comment]
Ok. Thanks for clarifying. This is a bug. Will look into it.

**Comment by pragnagopa** [comment]
@JunyiYi  - To support this, need to update RpcComplexDataSources.java [here](https://github.com/Azure/azure-functions-java-worker/blob/dev/src/main/java/com/microsoft/azure/functions/worker/binding/RpcComplexDataSources.java#L78) to include converting to a list of POJOs

here is a sample for doing this using Jackson using [TypeReference](https://fasterxml.github.io/jackson-core/javadoc/2.0.0/com/fasterxml/jackson/core/type/TypeReference.html)

```java
String jsonInStringArray = "[{\"id\":7500 , \"name\":\"pgopa\"}, {\"id\":7502 , \"name\":\"pgopa2\"}]";
List<Document> documentsList = mapper.readValue(jsonInStringArray, new TypeReference<ArrayList<Document>>() {});				
```
Also, here is sample code using GSON

```java
Type listOfTestObject = new TypeToken<List<Document>>(){}.getType();			
List<Document> list2 = gson.fromJson(jsonInStringArray, listOfTestObject);
```
Any ideas on how to use this TypeReference or TypeToken in RpcComplexDataSources?

**Comment by pragnagopa** [comment]
Binding to POJO Array is now supported. Here is an example for HttpTrigger with CosmosDBInput binding that receives a list of type Document (pojo)

```
@FunctionName("CosmosDBInputQueryPOJOArray")
    public HttpResponseMessage CosmosDBInputQueryPOJOArray(@HttpTrigger(name = "req", methods = { HttpMethod.GET,
            HttpMethod.POST }, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<Optional<String>> request,
            @CosmosDBInput(name = "item", databaseName = "%CosmosDBDatabaseName%", collectionName = "ItemsCollectionIn", connectionStringSetting = "AzureWebJobsCosmosDBConnectionString", sqlQuery = "SELECT f.id, f.name FROM f WHERE f.name = {name}") Document[] items,
            final ExecutionContext context) {
        context.getLogger().info("Java HTTP trigger processed a request.");

        // Parse query parameters
        String query = request.getQueryParameters().get("name");
        String name = request.getBody().orElse(query);

        if (items.length >= 2) {
            return request.createResponseBuilder(HttpStatus.OK).body("Hello, " + name).build();
        } else {
            return request.createResponseBuilder(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Did not find expected items in CosmosDB input list").build();
        }
    }

public static class Document {
        public String id;
        public String Description;
    }
```

**Comment by pragnagopa** [comment]
Fixed as part in commit #https://github.com/Azure/azure-functions-java-worker/commit/135fdf71a7f5f92fd4ae1c8cd429b8454e1e249c

- As long as the input is a valid json array, you can now bind to POJO array
- If input is a String array then you can bind to String[]

**Comment by dsyer** [comment]
That’s nice. The issue I raised was about binding to a `List<Foo>` though, and it doesn’t look that that works yet?

**Comment by pragnagopa** [comment]
Yes. I have opened issue #207  to track it.
