### ISSUE TITLE
Binding to `OutputBinding<List<T>>` and `HttpRequestMessage<T>` results in "Cannot locate the method signature..." error

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-java-worker#169]
#### Investigative information

Local dev using beta37 of Core Tools.

#### Repro steps

I'm trying to get the SignalR bindings to work on a Java Functions app. The source for the bindings I'm using are here:
 
https://github.com/Azure/azure-functions-signalrservice-extension
 
We are waiting for the proper API key to publish the NuGet package in the right namespace. In the meantime, I've temporarily published it here:
 
https://www.nuget.org/packages/AzureAdvocates.WebJobs.Extensions.SignalRService/0.3.0-alpha
 
I am actually trying to modify the azure-functions-java-library and azure-maven-plugins to create annotations for the bindings. However, I'm running into some trouble, so I am trying to get it to work without annotations first. I have the following project to reproduce the problems I'm having:
 
https://github.com/anthonychu/signalr-bindings-java-sample
 
The `negotiate` function works (if you run the app and go to http://localhost:7071/api/negotiate, it'll return an endpoint and an access key):
 
https://github.com/anthonychu/signalr-bindings-java-sample/blob/master/functionapp/src/main/java/com/example/Function.java#L7
 
However, I'm having trouble with the messages function in the same file. There are two issues:
 
**Output binding**
 
This is my biggest blocker as I can't move forward without getting this working.
 
I cannot figure out how to use the SignalR output binding. It's an `IAsyncCollector<SignalRMessage>`, the source can be found [here](https://github.com/Azure/azure-functions-signalrservice-extension/tree/master/src/SignalRServiceExtension). For reference, I have the JavaScript version of the same sample [here](https://github.com/Azure/azure-functions-signalrservice-extension/tree/master/samples/simple-chat/js/functionapp/messages); it works fine. I'm trying to build the exact same thing in Java.
 
No matter what I do, I get the "Cannot locate the method signature with the given input" error.
 
**Strongly typed HTTP Trigger**
 
I can sort of get around this, as `HttpRequestMessage<String>` works. But I would like to bind to `HttpRequestMessage<ChatMessage>` instead. If I use `HttpRequestMessage<ChatMessage>` and post an object in the body `{"sender":"foo", "text":"bar"}`, I get "Cannot locate the method signature with the given input" as well.
 
My JAVA_HOME is set to:
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
 
Thanks!

**Comment by asavaritayal** [comment]
Assigning the investigation to this sprint.

**Comment by pragnagopa** [comment]
Dup of https://github.com/Azure/azure-functions-java-worker/issues/207
