### ISSUE TITLE
Add support for JAVA_OPTS

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#171]
- Needed to Wire up for Application Profile Management for example using new relic

**Comment by pragnagopa** [comment]
Any command line arguments that need to passed to java.exe can be set via appSetting
languageWorkers:java:arguments

**Comment by selvasingh** [comment]
@pragnagopa JAVA_OPTS is the traditional environment variable for wiring up APM agents

**Comment by darewreck54** [comment]
@prabgupta Can you be more specific what appSettinglangaugeWorkers:java:arguments would be placed?

In an azure function there is the host.json and then the local.settings.json (for env variables).

Where would this be placed when executing locally and from azure (would this be on the blade settings)?

Thanks,
Derek

**Comment by pragnagopa** [comment]
@darewreck54 - Use langaugeWorkers:java:arguments for passing any commandline arguments you need to pass for java.exe

For adding connection string via appsettings, please see https://github.com/Azure/azure-functions-java-worker/issues/146

**Comment by pragnagopa** [comment]
Addressed in https://github.com/Azure/azure-functions-host/pull/3678

**Comment by kaushalp** [comment]
Is there an example that one can refer? I cannot find any documentation which discusses this scenario. I need to pass `-Djava.net.preferIPv4Stack=true` 

Should I be doing this? 
APP SETTING NAME | VALUE
-- | --
languageWorkers:java:arguments | JAVA_OPTS=-Djava.net.preferIPv4Stack=true

or this 
APP SETTING NAME | VALUE
-- | --
languageWorkers:java:arguments | JAVA_OPTS=-Djava.net.preferIPv4Stack=true

**Comment by pragnagopa** [comment]
@kaushalp - the option you are referring to is already part of the default JVM options we use. Please see : https://github.com/Azure/azure-functions-java-worker/blob/dev/worker.config.json#L7 for the complete list of JVM options.

I recently fixed typo for IPv4Stack and fix will be released by end of this month. For now, you can set the option explicitly

APP SETTING NAME | VALUE
-- | --
`languageWorkers:java:arguments `| `-Djava.net.preferIPv4Stack=true`

**Comment by kaushalp** [comment]
@pragnagopa Thanks. I was just using an example to see how the value needs be set. Can we update the Public facing documentation to include this. It will be easier for the users to refer this then.

**Comment by pragnagopa** [comment]
Doc issue: https://github.com/MicrosoftDocs/azure-docs/issues/30525

**Comment by kaushalp** [comment]
Thanks @pragnagopa
