### ISSUE TITLE
Error while deploying function app to azure with java runtime 

### ISSUE THREAD

**Issue by pragathikadaganchi** [Azure/azure-functions-java-worker#173]
error while deploying it to azure 
 <azure.functions.maven.plugin.version>1.0.0-beta-4</azure.functions.maven.plugin.version>
        <azure.functions.java.library.version>1.0.0-beta-5</azure.functions.java.library.version>
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Azure Java Functions 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ scanandgo ---
[INFO] Deleting C:\Users\pkada00\IdeaProject\scanandgo-backend\target
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ scanandgo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ scanandgo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\classes
[WARNING] /C:/Users/pkada00/IdeaProject/scanandgo-backend/src/main/java/com/safeway/kafka/CheckoutConsumer.java: C:\Users\pkada00\IdeaProject\scanandgo-backend\src\main\java\com\safeway\kafka\CheckoutConsumer.java uses or overrides a deprecated API.
[WARNING] /C:/Users/pkada00/IdeaProject/scanandgo-backend/src/main/java/com/safeway/kafka/CheckoutConsumer.java: Recompile with -Xlint:deprecation for details.
[WARNING] /C:/Users/pkada00/IdeaProject/scanandgo-backend/src/main/java/com/safeway/dao/ScanAndGoFunctionDAO.java: C:\Users\pkada00\IdeaProject\scanandgo-backend\src\main\java\com\safeway\dao\ScanAndGoFunctionDAO.java uses unchecked or unsafe operations.
[WARNING] /C:/Users/pkada00/IdeaProject/scanandgo-backend/src/main/java/com/safeway/dao/ScanAndGoFunctionDAO.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ scanandgo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\pkada00\IdeaProject\scanandgo-backend\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ scanandgo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ scanandgo ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:copy-dependencies (copy-dependencies) @ scanandgo ---
[INFO] Copying httpclient-4.5.3.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\httpclient-4.5.3.jar
[INFO] Copying jsr305-1.3.9.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\jsr305-1.3.9.jar
[INFO] Copying opencsv-4.2.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\opencsv-4.2.jar
[INFO] Copying commons-text-1.3.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\commons-text-1.3.jar
[INFO] Copying commons-validator-1.6.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\commons-validator-1.6.jar
[INFO] Copying j2objc-annotations-1.1.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\j2objc-annotations-1.1.jar
[INFO] Copying animal-sniffer-annotations-1.14.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\animal-sniffer-annotations-1.14.jar
[INFO] Copying commons-beanutils-1.9.3.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\commons-beanutils-1.9.3.jar
[INFO] Copying commons-lang3-3.7.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\commons-lang3-3.7.jar
[INFO] Copying handy-uri-templates-2.1.6.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\handy-uri-templates-2.1.6.jar
[INFO] Copying re2j-1.1.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\re2j-1.1.jar
[INFO] Copying httpcore-4.4.5.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\httpcore-4.4.5.jar
[INFO] Copying org.everit.json.schema-1.8.0.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\org.everit.json.schema-1.8.0.jar
[INFO] Copying commons-collections4-4.1.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\commons-collections4-4.1.jar
[INFO] Copying error_prone_annotations-2.0.18.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\error_prone_annotations-2.0.18.jar
[INFO] Copying json-20180130.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\json-20180130.jar
[INFO] Copying guava-22.0.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\guava-22.0.jar
[INFO] Copying snappy-java-1.1.7.1.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\snappy-java-1.1.7.1.jar
[INFO] Copying joda-time-2.9.4.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\joda-time-2.9.4.jar
[INFO] Copying kafka-clients-2.0.0.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\kafka-clients-2.0.0.jar
[INFO] Copying lz4-java-1.4.1.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\lz4-java-1.4.1.jar
[INFO] Copying commons-codec-1.9.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\commons-codec-1.9.jar
[INFO] Copying commons-digester-1.8.1.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\commons-digester-1.8.1.jar
[INFO] Copying commons-collections-3.2.2.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\commons-collections-3.2.2.jar
[INFO] Copying commons-logging-1.2.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\commons-logging-1.2.jar
[INFO] Copying slf4j-api-1.7.25.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\slf4j-api-1.7.25.jar
[INFO] Copying mongo-java-driver-3.6.3.jar to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\lib\mongo-java-driver-3.6.3.jar
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ scanandgo ---
[INFO] Building jar: C:\Users\pkada00\IdeaProject\scanandgo-backend\target\scanandgo-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- azure-functions-maven-plugin:1.0.0-beta-4:package (package-functions) @ scanandgo ---
[INFO] 
[INFO] Step 1 of 7: Searching for Azure Functions entry points
[INFO] Reflections took 1010 ms to scan 29 urls, producing 22 keys and 2282 values 
[INFO] 13 Azure Functions entry point(s) found.
[INFO] 
[INFO] Step 2 of 7: Generating Azure Functions configurations
[INFO] Generation done.
[INFO] 
[INFO] Step 3 of 7: Validating generated configurations
[INFO] Validation done.
[INFO] 
[INFO] Step 4 of 7: Saving empty host.json
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\host.json
[INFO] 
[INFO] Step 5 of 7: Saving configurations to function.json
[INFO] Starting processing function: getItemByScanCode
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\getItemByScanCode\function.json
[INFO] Starting processing function: removeItem
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\removeItem\function.json
[INFO] Starting processing function: vposCheckOutCart
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\vposCheckOutCart\function.json
[INFO] Starting processing function: addItemToCart
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\addItemToCart\function.json
[INFO] Starting processing function: getReceipt
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\getReceipt\function.json
[INFO] Starting processing function: removeItems
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\removeItems\function.json
[INFO] Starting processing function: salesTransaction
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\salesTransaction\function.json
[INFO] Starting processing function: checkOutCart
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\checkOutCart\function.json
[INFO] Starting processing function: clearCart
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\clearCart\function.json
[INFO] Starting processing function: insertReceipt
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\insertReceipt\function.json
[INFO] Starting processing function: viewCart
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\viewCart\function.json
[INFO] Starting processing function: createItems
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\createItems\function.json
[INFO] Starting processing function: uploadCSV
[INFO] Successfully saved to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\uploadCSV\function.json
[INFO] 
[INFO] Step 6 of 7: Copying JARs to staging directoryC:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging
[INFO] Copied successfully.
[INFO] 
[INFO] Step 7 of 7: Installing function extensions if needed
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 74.75 ms for C:\Users\pkada00\IdeaProject\scanandgo-backend\extensions.csproj.
  extensions -> C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging\bin\extensions.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.12

[WARNING] Local version of Azure Functions Core Tools (2.0.1-beta.34) does not match the latest (2.0.1-beta.38). Please update it for the best experience. See: https://aka.ms/azfunc-install
[INFO] Function extension installation done.
[INFO] Successfully built Azure Functions.
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-resources) @ scanandgo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-bin) @ scanandgo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\pkada00\IdeaProject\scanandgo-backend\bin
[INFO] 
[INFO] --- azure-functions-maven-plugin:1.0.0-beta-4:deploy (default-cli) @ scanandgo ---
[INFO] Starting deployment to Azure Function App Pragathi-staging...
[INFO] Authenticate with Azure CLI 2.0
[INFO] Updating Azure Function App...
[INFO] Successfully updated Azure Function App Pragathi-staging
[INFO] 
[INFO] Step 1 of 4: Creating ZIP file...
[INFO] Successfully saved ZIP file at C:\Users\pkada00\IdeaProject\scanandgo-backend\target\azure-functions\Pragathi-staging.zip
[INFO] 
[INFO] Step 2 of 4: Uploading ZIP file to Azure Storage...
[INFO] Successfully uploaded ZIP file to https://pragathistaging9bdc.blob.core.windows.net/java-functions-deployment-packages/Pragathi-staging.20180907225515965.zip
[INFO] 
[INFO] Step 3 of 4: Deploying Azure Function App with package...
[INFO] 
[INFO] Step 4 of 4: Deleting deployment package from Azure Storage...
[INFO] Successfully deleted deployment package Pragathi-staging.20180907225515965.zip
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:42 min
[INFO] Finished at: 2018-09-07T22:56:07-07:00
[INFO] Final Memory: 63M/493M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.0.0-beta-4:deploy (default-cli) on project scanandgo: Async operation failed with provisioning state: failed: OnError while emitting onNext value: com.microsoft.azure.PollingState.class -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1

**Comment by pragnagopa** [comment]
closing this as dup of https://github.com/Azure/azure-functions-java-worker/issues/174
