### ISSUE TITLE
Consolidate documentation on different ways to deploy java functions

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#175]
Instructions https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven focus on using mvn plugin to get started.
We need to document other ways to deploying java functions for example
- using azure cli and upload zip

**Comment by asavaritayal** [comment]
Need the API / CLI command for zip deploy.

**Comment by asavaritayal** [comment]
A few different methods are now documented here: https://medium.com/@maninder.bindra/continuous-deployment-of-azure-functions-written-in-java-using-azure-pipelines-azure-devops-dfb00829f364
