### ISSUE TITLE
Operation has timed out  due to failure to start language worker.

### ISSUE THREAD

**Issue by arun-bn** [Azure/azure-functions-java-worker#176]
Once a running server less function, gets 'unloaded', the next call fails with this error.

_Function (pwt) Error: Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . Failed to start language worker process for: java. D:\Program Files\Java\zulu8.23.0.3-jdk8.0.144-win_x64\bin\java exited with code -1 . Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. The operation has timed out. Failed to start language worker process for: java. The operation has timed out.
Session Id: 7079178b0aca465dac434e237a86d138
Timestamp: 2018-09-11T11:54:32.213Z_

The only way to fix this is to use the portal and restart the function.

#### Investigative information

Please provide the following:

- Timestamp: 2018-09-11T11:54:32.213Z
- Function App name: 
- Function name(s) (as appropriate): pwt
- Invocation ID: 7079178b0aca465dac434e237a86d138
- Region: eastUS

#### Repro steps

Provide the steps required to reproduce the problem:

1. Wait for 20+ minutes for system to unload the function.
2. Make a call to the function and we get this error.

Provide a description of the expected behavior.

The function is a based on a webhook. It should respond with a JSON object.

#### Actual behavior
We are getting an Error 500 as mentioned.

#### Known workarounds
Restart the function from portal.

#### Related information 
I am aware of #174  but it seems it going down the rabbit hole of deployment. In my case, it is not deployment, just cold starts times out.

Provide any related information 
I have opened a support ticket with MS and was directed to use this resource.
I am made aware of the limitations of  consumption plan.  At present, I am interested in fixing the timeout issue and longer term think of using a dedicated plan.

https://blogs.msdn.microsoft.com/appserviceteam/2018/02/07/understanding-serverless-cold-start/

* Programming language used  : Java

**Comment by pragnagopa** [comment]
Fix is rolled out. Closing this issue. Please reopen if you still see the same error.

**Comment by caroltheuri** [comment]
i still have the same problem. Kindly help
