### ISSUE TITLE
Use latest Java version preinstalled on AppService

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#178]
To mitigate [lazy loading issue with Java.exe](https://github.com/Azure/azure-functions-host/issues/3081),
java worker points to[%JAVA_HOME%../../../FunctionsJava/zulu8.30.0.1-jdk8.0.172-win_x64/bin/java]( https://github.com/Azure/azure-functions-java-worker/blob/dev/worker.config.json#L11) on AppService.

Need to remove [profiles](https://github.com/Azure/azure-functions-java-worker/blob/dev/worker.config.json#L9) section, once latest version of java 1.8 is preinstalled in AppService environment.

**Comment by pragnagopa** [comment]
FYI: @shrishrirang

**Comment by pragnagopa** [comment]
Moving to it sprint 34 to continue conversation with AppService team and to co-ordinate UI changes needed.

**Comment by asavaritayal** [comment]
Waiting for ANT78 to complete.

**Comment by pragnagopa** [comment]
Update arguments to 
-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -noverify
