### ISSUE TITLE
Azure function java worker Jackson Core 2.9.6 Dependecy

### ISSUE THREAD

**Issue by albertodema** [Azure/azure-functions-java-worker#182]
Hi I am experiencing some blockers while trying to use (for model scoring) spark on Azure Functions.
I managed to find an exception that is basically blocking any spark operation:
com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.9.6
 Azure Functions Java Worker has Jackson 2.9.6 as dependency and spark 2.2 cannot work with anything >2.6.
So even if I try to exclude Jackson Core 2.9 from dependencies in my function pom.xml it is in reality anyway used by the worker and this causes spark to fail.
Is there a way to have the Azure Worker to use Jackson Core 2.6?

**Comment by pragnagopa** [comment]
Notes from @selvasingh 
We should not downgrade this. A luxury version is to make sure developers can plug in a lower version of Jackson, if they like to.

**Comment by albertodema** [comment]
Hi I was able to have spark working locally with those modifications to the pom.xml file of azure-functions-worker project:
		_**<dependency>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-netty-shaded</artifactId>
			<version>1.15.0</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.6.5</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.6.5</version>
		</dependency>**_

The first one is just the same dependecy but shaded in order to avoid collision with spark that is using netty 4.0, the remaining two are referring to an older version of jackson that works with spark.

Unfortunately I cannot deploy this version on azure functions because the azure-java-worker.jar is placed in a location with readonly permissions.

I am currently stuck at this point and evaluating other cloud alternatives to progress.

**Comment by pragnagopa** [comment]
@brunoborges / @JonathanGiles  - Any ideas on how to package dependencies for azure-fucntions-java-worker in a way that gives the ability for users to override worker dependencies with their own?

**Comment by asavaritayal** [comment]
Closing issue in favor of https://github.com/Azure/azure-functions-java-worker/issues/183
