### ISSUE TITLE
Request for Java 10

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-java-worker#184]
A customer has requested Java 10 [here](https://github.com/Azure/Azure-Functions/issues/965).

**Comment by pragnagopa** [comment]
cc : @asavaritayal , @eduardolaureano 
As of now the plan is to support only LTS versions of Java.

**Comment by CodySC** [comment]
Now that Java 11 is out is there a timeline for that?

**Comment by pragnagopa** [comment]
No exact ETA.  We have an existing issue for Java 11 https://github.com/Azure/azure-functions-java-worker/issues/120 Will post update there as soon as we have a plan.

**Comment by pragnagopa** [comment]
Closing as won't fix.
