### ISSUE TITLE
ETA for Java Functions GA

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#191]
_From @pragathikadaganchi on October 4, 2018 5:45_

I have a question regarding azure functions using java. Currently we developed an application using azure serverless functions in java and now are not having any breaking changes with  Azure functions Runtime version: 2.0.12115.0 (beta). we would like to continue our project with java which is in preview. And we are expecting to go in production by end of the year. When can we expect java to be GA? can we continue with java preview version and go live?

_Copied from original issue: Azure/Azure-Functions#976_

**Comment by pragnagopa** [comment]
cc: @asavaritayal , @jeffhollan 
Java support is still in preview. We do not recommend going to production before GA. I will update the issue when I have an ETA for GA.

**Comment by pragathikadaganchi** [comment]
How soon can we expect an ETA for GA?

**Comment by asavaritayal** [comment]
General availability of Java in Azure Functions is expected to be available by the end of this calendar year. We'll be posting updates regarding the announcement here - https://github.com/Azure/app-service-announcements/issues

**Comment by berlix** [comment]
Hi, Java support is still in preview. Are there any updates on an ETA for GA?

**Comment by rozaydin** [comment]
Hi, any update for the ETA date ?
