### ISSUE TITLE
Document VSTS deployment script using maven

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#199]

**Comment by asavaritayal** [comment]
@rloutlaw is tracking this. In the meantime, here's a post documenting this - https://medium.com/@maninder.bindra/continuous-deployment-of-azure-functions-written-in-java-using-azure-pipelines-azure-devops-dfb00829f364

**Comment by pragnagopa** [comment]
@rloutlaw /@asavari - is there a doc issue for this? We do need to capture vsts deployment that includes a trigger other than HttpTrigger as there is some confusion on how to install extensions when using storage triggers or eventhub triggers
