### ISSUE TITLE
Enable binding to List<POJO>

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#207]
By default, com.fasterxml.jackson.core converts a Json string array with valid Json object to POJO array

To support binding to List<POJO>,  RpcComplexDataSources.java [here](https://github.com/Azure/azure-functions-java-worker/blob/dev/src/main/java/com/microsoft/azure/functions/worker/binding/RpcComplexDataSources.java#L78) needs to be updated to include converting to a list of POJOs

here is a sample for doing this using Jackson using [TypeReference](https://fasterxml.github.io/jackson-core/javadoc/2.0.0/com/fasterxml/jackson/core/type/TypeReference.html)

```java
String jsonInStringArray = "[{\"id\":7500 , \"name\":\"pgopa\"}, {\"id\":7502 , \"name\":\"pgopa2\"}]";
List<Document> documentsList = mapper.readValue(jsonInStringArray, new TypeReference<ArrayList<Document>>() {});				
```
Also, here is sample code using GSON

```java
Type listOfTestObject = new TypeToken<List<Document>>(){}.getType();			
List<Document> list2 = gson.fromJson(jsonInStringArray, listOfTestObject);
```
Needs investigation.

**Comment by pragnagopa** [comment]
@dsyer - I am trying to asses the priority for this issue. Is this a blocker for your scenario?

**Comment by dsyer** [comment]
Yes, it's a blocker. My scenario is only a demo, but I'm sure you can imagine other people will want to do the same thing. The type information is available, so it's probably not a huge amount of work.

**Comment by anthonychu** [comment]
Blocker here as well, although I'm experiencing this with an output binding (#169). Thanks!

**Comment by pragnagopa** [comment]
This fix needed a major refactoring around how worker converts to the types needed by the method signature.
@anthonychu - Please try with the latest bits from dev branch and let me know if it unblocks your scenario.
