### ISSUE TITLE
CosmosDBInput binding to Array or Collection types

### ISSUE THREAD

**Issue by Trosky** [Azure/azure-functions-java-worker#214]
It seems not to be possible to bind multiple results of a cosmosdb query to a Collection or Array of a POJO class. 

We tried to bind `Optional<List<Order>>`, `Optional<Order[]>`, `List<Order>` and `Order[]`.

Example code:
```
 @FunctionName("userOrders")
    public HttpResponseMessage getUserOrders(
            @HttpTrigger(name = "req",
                    methods = {HttpMethod.GET},
                    authLevel = AuthorizationLevel.ANONYMOUS,
                    route = "user/{userId}/orders")
                    HttpRequestMessage<Order> orderRequest,
            @BindingName("userId") String userId,
            @CosmosDBInput(name = "order",
                    databaseName = "someDbName",
                    collectionName = "orders",
                    sqlQuery = "SELECT * FROM c WHERE c.userid = {userId}",
                    connectionStringSetting = "AzureCosmosDBConnection") Order[] order,
            final ExecutionContext context) {
        context.getLogger().info("OrderFunction!");

        if (order.length > 0) {
            return orderRequest.createResponseBuilder(HttpStatus.OK).body(Arrays.asList(order)).build();
        } else {
            return orderRequest.createResponseBuilder(HttpStatus.NOT_FOUND).build();
        }
    }
```

#### Actual behavior

- If you use as type the `Order[]` array you get an error: `Cannot locate the method signature with the given input`
- If you use as type the `Collection<Order>` you get a `ArrayList<LinkedHashMap>`.

#### Expected behavior

Some way to get a correctly typed Array or Collection of an POJO. 

#### Known workarounds

Use `Optional<String>` and deserialize the POJO by hand.

#### Related information 

Provide any related information 

* Programming language used: Java
* Bindings used: CosmosDBInputBinding

**Comment by pragnagopa** [comment]
This issue is addressed and fix will part of next release. You can binding to Order[]
Here is a related issue #207  tracking fix to support binding to List
