### ISSUE TITLE
Javadoc and sample consistent sample code is missing.

### ISSUE THREAD

**Issue by nicenemo** [Azure/azure-functions-java-worker#24]
Javadoc is missing on a lot of code.
Please provide useful API documentation. Not "a, this is an a" kind of documentation.

I Now have to guess from .NET, NodeJS, Java Documentation and outdated blogposts on how stuff works.
This sometime breaks due to API changes.

**Comment by JunyiYi** [comment]
Good suggestion of Javadoc for java-core packages.

**Comment by JunyiYi** [comment]
We have introduced the javadoc toolchain, and we have also written some of the Javadocs. I will close this issue and add more documentation later.
