### ISSUE TITLE
Java Function Language worker process exited 

### ISSUE THREAD

**Issue by jcbrooks92** [Azure/azure-functions-java-worker#245]
#### Investigative information

Please provide the following:

- Timestamp: 11/16 08/31:45
- Function App name: jebrook-javafunc
- Function name(s) (as appropriate): 
- Invocation ID:
- Region: South Central US
- Plan : Consumption Plan 

#### Repro steps

Provide the steps required to reproduce the problem:
1. Deploy a java function
2. invoke it to start the language worker 
3. leave it idle for 20 minutes until the job host shuts down

#### Expected behavior

The java worker shutting down due to the job host shutting down after an idle time probably shouldn't show up as an error as this may incorrectly alert users of a failure where as it was just shutting down do to the parent process shutting down. In kusto it shows a level 2 failure leading users to believe the worker is crashing even though it is just shutting down.

#### Actual behavior

Language Worker Process exited.
--
  **| LogLevel | Error**
  | Category | Worker.java.e33f1654-894b-4868-917d-7dda56549a7d

function logs from CUS 
FunctionsLogs
| where AppName =~ "jebrook-javafunc"
| where TIMESTAMP > datetime(2018-11-16 08:16:58.8142666) and TIMESTAMP < datetime(2018-11-16 11:16:58.8142666)
| project TIMESTAMP , Level,Summary, Details 

![image](https://user-images.githubusercontent.com/18233035/48748663-9adeee80-ec45-11e8-96a7-ac976cc184c8.png)

#### Known workarounds

NA

#### Related information 
Function Host
{
  "scriptFile": "..\\functions.jar",
  "entryPoint": "xxxx",
  "bindings": [
    {
      "type": "blobTrigger",
      "name": "blob",
      "direction": "in",
      "dataType": "binary",
      "connection": "xxx",
      "path": "xxxx/{name}"
    },
    {
      "type": "serviceBus",
      "name": "$return",
      "direction": "out",
      "queueName": "xxxx",
      "connection": "ServiceBus",
      "access": "MANAGE"
    }
  ]
}

**Comment by asavaritayal** [comment]
@jcbrooks92 Is your Function App hosted on the Consumption plan?

**Comment by veerapanenirakesh** [comment]
I have the same issue. Is there a work around or solution

**Comment by jcbrooks92** [comment]
I believe this was fixed, closing for now.
