### ISSUE TITLE
Managed Service Identity (MSI) with Java functions

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#249]
Tracking issue to try and document using MSI authentication with java functions.

**Comment by pragnagopa** [comment]
cc @paulbatum  @mattchenderson 

@asavaritayal  - Did you get a chance to MSI with Java functions?

**Comment by yevster** [comment]
You can use MSI this way:
```java
var azure = Azure.authenticate(new AppServiceMSICredentials(AzureEnvironment.AZURE))
				.withSubscription(cdnSubscriptionId);
```
Then, use the "azure" object as you would normally when using the Azure SDK.

I hope to be able to get a code sample up soon, but in the meanwhile, this should be added to the documentation.

**Comment by yevster** [comment]
[Pull request here](https://github.com/MicrosoftDocs/azure-docs/pull/34347)
