### ISSUE TITLE
Set up a nightly build for testing the language worker end to end

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-java-worker#252]
Related to: https://github.com/Azure/azure-functions-host/issues/3546

We have nightly build for core tools that references the latest web host package (generated from webhost nightly build). We need a nightly build for Java worker that consumes the generated CLI (from nightly build) and runs E2E tests against that.

**Nightly builds current state:**
Webhost (done)-> CLI (done)-> Java Worker (pending)

**Comment by pragnagopa** [comment]
@anirudhgarg  / @amamounelsayed  - I will pick this up.

**Comment by kaibocai** [comment]
Close this issue as we have nightly build E2E tests now. Thanks.
