### ISSUE TITLE
BlobTrigger - ClassCastException when specifying "dataType" parameter

### ISSUE THREAD

**Issue by daniel-rocha** [Azure/azure-functions-java-worker#256]
#### Investigative information

Please provide the following:

- Timestamp: 2018-12-27T07:47:22.749
- Function App name: java-bindings-function-app
- Function name(s) (as appropriate): blobprocessorString and blobprocessorPojo
- Invocation ID: Id=e44d3f88-dae4-422d-ac49-89e8f4a97120 and Id=1bc622d1-1eea-4074-b7c4-f27d0eb18afa
- Region: Southeast Asia

#### Repro steps

Provide the steps required to reproduce the problem:

1. Deploy function app containing Java functions with BlobTrigger annotation.
2. Upload a text file to the blob storage container.
3. Watch as only the function with binary dataType works. 

#### Expected behavior

All functions work well, and display the content of the blobs on the log. According to the documentation for the BlobTrigger annotation ( https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.functions.annotation.blobtrigger?view=azure-java-stable ), the dataType parameter can be:

binary: byte[]
string: String
"": POJO

It was expected that all three parameters worked well.

#### Actual behavior

Only the function whose BlobTrigger parameter is byte[] works.

#### Known workarounds

Use the byte[] version, convert it to String then to the appropriate POJO.

#### Related information 

Provide any related information 

* Programming language used: Java
* Links to source: https://github.com/daniel-rocha/azure-functions-java-bindings/tree/master/src/main/java/com/danielrocks/function/blob/trigger
* Bindings used
<details>
<summary>Source</summary>

```java
    @FunctionName("blobprocessorString")
    public void run(
      @BlobTrigger(name = "file",
                   dataType = "string",
                   path = "myblob/{name}",
                   connection = "Storage_Account_Connection_String") String content,
      @BindingName("name") String filename,
      final ExecutionContext context) {
        // log 
        context.getLogger().info("Name: " + filename + " Content: " + content);
    }
```

```java
    @FunctionName("blobprocessorPojo")
    public void run(
      @BlobTrigger(name = "file",
                   dataType = "",
                   path = "myblob/{name}",
                   connection = "Storage_Account_Connection_String") ToDoItem content,
      @BindingName("name") String filename,
      final ExecutionContext context) {
        // log 
        context.getLogger().info("Name: " + filename);

        // do something with blob
        context.getLogger().info("ToDoItem is: " + content.getId() + " - " + content.getDescription());
    }
```
</details>

**Comment by pragnagopa** [comment]
@daniel-rocha - Can you please share your function method signature?

**Comment by daniel-rocha** [comment]
`
  @FunctionName("blobprocessorPojo")
  public void run(
    @BlobTrigger(
      name = "file",
      dataType = "",
      path = "samples-workitems/{name}",
      connection = "Storage_Account_Connection_String") 
    ToDoItem content,
    @BindingName("name") String filename,
    final ExecutionContext context) 

`

**Comment by pragnagopa** [comment]
This is a bug. Thanks for reporting. Sent a PR with the fix. Next release will include fix for this. Specifying `dataType` to bind to POJO is not required.
