### ISSUE TITLE
Method overloading in Functions

### ISSUE THREAD

**Issue by brokencranium** [Azure/azure-functions-java-worker#26]
I am triggering a function from EventHub but the message provided from event hub will vary. Is it possible to overload the methods. I am setting the point of entry to the overloaded methods in function.json. 

For testing purposes I am using a HTTPTrigger and passing different message types and I get the below listed error.

Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
[10/26/2017 21:56:38]   at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:33)
... 

If I comment out one of the overloaded method then it works as expected. 

Is this a right place to post such issues? 

Issue can be reproducible with the code listed below.
https://github.com/brokencranium/functions-method-overloading

**Comment by paulbatum** [comment]
Today, there is no support for overloading in functions (across all the languages). You need to write the code yourself to detect the type of message and dispatch appropriately. In C# that might look something like this:

```csharp
public static async Task Run(
    EventData[] sensorEvent,
    PartitionContext partitionContext,
    IAsyncCollector<EventData> outputWeatherData,
    IAsyncCollector<EventData> outputSeismicData,
    TraceWriter log)
{

    foreach (var sensorData in sensorEvent)
    {
        SensorType sensorType = SensorType.Unknown;

        try
        {                    
            if (sensorData.Properties.ContainsKey("SensorType"))
            {
                System.Enum.TryParse(sensorData.Properties["SensorType"].ToString(), out sensorType);
            }

            if (sensorType == SensorType.Weather)
            {
                // do something
            }
            else if (sensorType == SensorType.Seismic)
            {
                // do something else
            }                        
        }
        catch(Exception ex)
        {
            // handle exception
        }
    }                                    
}
```

However I should note that this code snippet is relying on the ability to bind to EventData, which is the .NET equivalent of the Java type `com.microsoft.azure.eventhubs.EventData`. So to handle this scenario you might need to be able to write your Java function to accept this type, which I don't think is supported yet. Hey @christopheranderson, does our Event Hubs support in Java allow you to access message properties?

**Comment by brokencranium** [comment]
I am not sure if its a vagary, function execution is successful even when passing invalid types to the functions.  

Instructions to recreate the issue is at https://github.com/brokencranium/functions-method-overloading

Thank you for your earlier response.

**Comment by JunyiYi** [comment]
Java does support some kinds of overloading. But according to your sample, it is not the case because both of the messages could be serialized successfully to both Java types (we use Jackson internally), so it is actually an ambiguous call.
