### ISSUE TITLE
Java Azure function does not allow create http client post

### ISSUE THREAD

**Issue by anky2209** [Azure/azure-functions-java-worker#265]
Azure function which is in App service plan as we want point to site connectivity.
It was working fine for many days.
for last few days, we facing below issue

**failed: connect: Address is invalid on local machine, or port is not valid on remote machine**

I have already followed this ticket https://github.com/Azure/azure-functions-java-worker/issues/139.
Kindly help @pragnagopa

**Comment by anky2209** [comment]
It looks like Function App is still using IPv6 stack

**Comment by pragnagopa** [comment]
Functions launches java.exe with `-Djava.net.preferIPV4Stack=true`.  This issue might be related to #246

**Comment by erik-olsen-idexx** [comment]
I found that the option needed to be w/ a lowercase 'v' e.g.
-Djava.net.preferIP**v**4Stack=true
in the application settings of the function app.

**Comment by kulkarnisonia16** [comment]
This is fixed and released.
