### ISSUE TITLE
Serverless function stops reading properties (application setting) during loading back for execution.

### ISSUE THREAD

**Issue by arun-bn** [Azure/azure-functions-java-worker#269]
The application works fine but suddenly while waking up to execute, it comes back to say it cannot read the application settings. If we stop and start it will not work but we disable and enable the function, it starts working again.

We use the following code to read the application settings.
_System.getenv("mysetting");_

#### Investigative information

Please provide the following:

- Timestamp: 
DATE (UTC) 2019-02-04 20:25:50.353
- Function App name:  
- Function name(s) (as appropriate):
- Invocation ID:  Id=16d07357-f014-4902-9581-881867d763ad
- Region: US EAST

#### Repro steps

Provide the steps required to reproduce the problem:

#### Related information 
We get the following logs 
Result: Failure
Exception: NoClassDefFoundError: Could not initialize class com.amig.yyyy.Constants
Stack: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)

Constants.java has the read from getenv(xxx), code and declared static. So if it errors out, we will get teh No Class Def  Found Error.

* Programming language used  **Java**
* Links to source
* Bindings used

**Comment by kulkarnisonia16** [comment]
Is this still happening?

**Comment by arun-bn** [comment]
In production, we have switched to service plan, which does not unload the function. But obviously it does go back on the promise of  serverless functions.

I do have a version in Q/A which keeps this function alive by another function.  Also have another  version in dev that is kept as is. We do notice that the issue used to happen uptil recently.

I will have to review the logs, to see if this issue has disappeared now. Was anything done recently to fix this?


Arun
