### ISSUE TITLE
Not able to redeploy Azure Functions

### ISSUE THREAD

**Issue by ginexitsolution** [Azure/azure-functions-java-worker#279]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by ginexitsolution** [comment]
Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.3.0:deploy (default-cli) on project HttpFunctionforTryg: Website with given name HttpFunctionTest already exists. OnError while emitting onNext value: retrofit2.Response.class -> [Help 1]

**Comment by anthonychu** [comment]
Can you check if the function app is in the same subscription as you are deploying to?

**Comment by ginexitsolution** [comment]
I had set the subcription bere deploy.

When i changed the name of project create automatically,it was deploying.

Can we add vnet configuration in this deployment?


Regards,

Al Shafeek B

**Comment by pragnagopa** [comment]
@ginexitsolution  - Here is info on VNET integration:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-vnet

Please reopen if run into issues.
