### ISSUE TITLE
Add support for Java functions on Linux function app 

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#283]
Tracking item to add support for running java function on Linux function app 
- Provide a custom image for Linux and KEDA

**Comment by pragnagopa** [comment]
cc @FabianMeiswinkel

**Comment by jhauray** [comment]
+1

**Comment by amamounelsayed** [comment]
We are now supporting java8 images for linux,
mcr.microsoft.com/azure-functions/java:3.0-java8
mcr.microsoft.com/azure-functions/java:3.0-java8-appservice 

https://github.com/Azure/azure-functions-docker
