### ISSUE TITLE
Move to AppService JRE after ANT 83 deployment

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#292]
Fix needed to move to AppService JRE is checked in ANT83.  Remove appServiceEnvironment from https://github.com/Azure/azure-functions-java-worker/blob/dev/worker.config.json#L10

**Comment by fabiocav** [comment]
Blocked on ANT 83 deployment.

**Comment by selvasingh** [comment]
Added @selvasingh

**Comment by pragnagopa** [comment]
This is addressed in commit #https://github.com/Azure/azure-functions-java-worker/commit/40096767c91b5456b1093e9f86b8ecfa7c09f48a

**Comment by pragnagopa** [comment]
Released https://github.com/Azure/azure-functions-java-worker/releases/tag/1.5.0
