### ISSUE TITLE
Spring Cloud Functions in Azure Functions

### ISSUE THREAD

**Issue by kulkarnisonia16** [Azure/azure-functions-java-worker#303]
Quick start and developer guide
Sample code for top triggers and bindings

**Comment by kaibocai** [comment]
Spring cloud function quikc start doc can be found https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure?toc=%2Fazure%2Fazure-functions%2Ftoc.json. We will keep this doc up to date. 

Create new issue to trigger triggers and bindings samples #706
