### ISSUE TITLE
 Azure KeyVault SDK - getSecret throws java.lang.ClassCastException 

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#306]
We have identified an issue with using Key vault SDK getSecret  API in Azure Functions. We are actively working on rolling out a fix. Until then please add follow instructions app settings to mitigage: 
- Add AppSetting Key `languageWorkers:java:defaultExecutablePath` with value set to `D:\Program Files\Java\jre1.8.0_181\bin\java`
- App setting key `WEBSITE_USE_PLACEHOLDER` with value set to `0`

**NOTE: This will increase cold starts for java functions**

**Comment by ielcoro** [comment]
We lost almost a day trying to workaround this in a critical path of our system, however we found another workaround that maybe does not increase cold starts. It looks like between versions the default order for java security providers was modified from this:

```
security.provider.1=sun.security.provider.Sun
security.provider.2=sun.security.rsa.SunRsaSign
security.provider.3=sun.security.ec.SunEC
security.provider.4=com.sun.net.ssl.internal.ssl.Provider
security.provider.5=com.sun.crypto.provider.SunJCE
security.provider.6=sun.security.jgss.SunProvider
security.provider.7=com.sun.security.sasl.Provider
security.provider.8=org.jcp.xml.dsig.internal.dom.XMLDSigRI
security.provider.9=sun.security.smartcardio.SunPCSC
security.provider.10=sun.security.mscapi.SunMSCAPI
```

To this: 

```
security.provider.1=sun.security.mscapi.SunMSCAPI
security.provider.2=sun.security.rsa.SunRsaSign
security.provider.3=sun.security.ec.SunEC
security.provider.4=com.sun.net.ssl.internal.ssl.Provider
security.provider.5=com.sun.crypto.provider.SunJCE
security.provider.6=sun.security.jgss.SunProvider
security.provider.7=com.sun.security.sasl.Provider
security.provider.8=org.jcp.xml.dsig.internal.dom.XMLDSigRI
security.provider.9=sun.security.smartcardio.SunPCSC
security.provider.10=sun.security.provider.Sun
```

So we use this code before calling `getSecret`to reorder the security providers:

```java
setProviderOrder("SUN", 1);
setProviderOrder("SunRsaSign", 2);
setProviderOrder("SunEC", 3);
setProviderOrder("SunJSSE", 4);
setProviderOrder("SunJCE", 5);
setProviderOrder("SunJGSS", 6);
setProviderOrder("SunSASL", 7);
setProviderOrder("XMLDSig", 8);
setProviderOrder("SunPCSC", 9);
setProviderOrder("SunMSCAPI", 10);
```

>

**Comment by fabiocav** [comment]
This is resolved with the release currently being deployed. Please use https://github.com/Azure/app-service-announcements/issues/188 to track the deployment progress.
