### ISSUE TITLE
Inhance the number of RPS requests between host and Java worker

### ISSUE THREAD

**Issue by amamounelsayed** [Azure/azure-functions-java-worker#320]
#### Repro steps

	The simplest code is https://github.com/amamounelsayed/azure-functions-benchmark-host/tree/feature/java-benchmark-simple, 
	Use Forkpool instead of cachethreadpool: https://github.com/amamounelsayed/azure-functions-benchmark-host/tree/feature/java-benchmark-forkthreadpool
	Created a log https://github.com/amamounelsayed/azure-functions-benchmark-host/tree/feature/java-benchmark-logging
	Created client serve with bidirectional channel https://github.com/amamounelsayed/azure-functions-benchmark-host/tree/try/clent-server-grpc-doc
	Created unary request client server: https://github.com/amamounelsayed/azure-functions-benchmark-host/tree/try/clent-server-grpc-doc-unray
	Created unary asyn client server: https://github.com/amamounelsayed/azure-functions-benchmark-host/tree/try/clent-server-grpc-doc-unray-async

#### Related information 

Provide any related information 

Java-bench branch RPS,
8/25/2019 6:46:31 PM
Duration : 105
RPS(spot): 89
RPS(avg): 95
Status_200: 10038
Status_3xx: 0
Status_4xx: 0
Status_5xx: 0
Average Response Time: 1037

**Comment by pragnagopa** [comment]
@amamounelsayed  - please send PR to https://github.com/pragnagopa/azure-functions-benchmark-host adding benchmark Java worker

**Comment by amamounelsayed** [comment]
@pragnagopa https://github.com/pragnagopa/azure-functions-benchmark-host/pull/7 Thank you
