### ISSUE TITLE
Add Java Docker image.

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-java-worker#333]
As of this issue being filed, Azure Functions in Java are in public preview. However, they lack Docker images as with other languages being developed, ex. Node and Python.

**Comment by amamounelsayed** [comment]
@raztiff we are in the process of updating FuncExtensionBundles and we may not need it on our images anymore. Is there any reason to require it on the images or just spot checking?

**Comment by raztiff** [comment]
Thanks for replying :)

I was wanting to use the image for integration/functional testing functions or even test Java docker functionality.

**Comment by amamounelsayed** [comment]
We published for amd64
mcr.microsoft.com/azure-functions/java:2.0
mcr.microsoft.com/azure-functions/java:2.0-appservice

Please let us know if you there is anything we can enhance out product with.
