### ISSUE TITLE
Java function host failed to discover main classes for spring cloud function

### ISSUE THREAD

**Issue by Flanker32** [Azure/azure-functions-java-worker#338]
Function host can't find the main class of spring cloud functions and report error. Both in azure services and local.

#### Investigative information

Function core tools **2.7.1948**

#### Repro steps

1. Prepare a spring cloud function project, could do it by `git clone https://github.com/Azure-Samples/hello-spring-function-azure.git`.
2. Build the spring cloud function project by `mvn clean package`
3. Invoke the function locally by `mvn azure-functions:run`.
    * This issue could also repo in service side, just remove the `MAIN_CLASS` settings in azure function configuration

#### Expected behavior

The main class of the function should be automatically found. The MAIN_CLASS property should not need to be specified and users could access the function by `curl http://localhost:7071/api/hello -d "{\"name\":\"Azure\"}"`

#### Actual behavior

No response from curl, function host reports 
```
 java.lang.IllegalStateException: Failed to discover main class. An attempt was made to discover main class as 'MAIN_CLASS' environment variable, system property as well as entry in META-INF/MANIFEST.MF (in that order).
```

#### Known workarounds

Set the MAIN_CLASS in app settings, for local run, add a `local.settings.json` file with MAIN_CLASS specified

#### Related information 

Referred https://github.com/microsoft/azure-maven-plugins/issues/912

**Comment by jdubois** [comment]
I'm now doing the same thing with our new [Gradle plugin](https://github.com/microsoft/azure-gradle-plugins) and I have the same issue again.

To fix this temporarily, I need to do the same trick, which is copying the `local.settings.json` file after the plugin has run, but this isn't a nice developer experience.

**Comment by kulkarnisonia16** [comment]
![image](https://user-images.githubusercontent.com/10569526/78591784-d3f70f00-77f8-11ea-9412-55930a48424c.png)

**Comment by ferblaca** [comment]
Any progress with this problem? 

In my case, even adding the `local.settings.json` file with the `MAIN_CLASS` attribute correctly, when I package in [.zip format](https://learn.microsoft.com/en-us/azure/azure-functions/deployment-zip-push#cli) the `stagingDirectory` and deploy it in Azure with `az functionapp deployment source config-zip ...` I am still encountering this problem when making a request to the function:

```
Exception: IllegalArgumentException: Failed to locate main class
Stack: java.lang.IllegalStateException: Failed to discover main class. An attempt was made to discover main class as 'MAIN_CLASS' environment variable, system property as well as entry in META-INF/MANIFEST.MF (in that order).
    at org.springframework.cloud.function.utils.FunctionClassUtils.getStartClass(FunctionClassUtils.java:86)
    at org.springframework.cloud.function.utils.FunctionClassUtils.getStartClass(FunctionClassUtils.java:63)
    at org.springframework.cloud.function.adapter.azure.FunctionInvoker.<init>(FunctionInvoker.java:94)
```

**Comment by kaibocai** [comment]
Hi @ferblaca , I can not reproduce the issue on my local, can you share a repo that include the your code I can take a look then. Thanks.

**Comment by ferblaca** [comment]
> Hi @ferblaca , I can not reproduce the issue on my local, can you share a repo that include the your code I can take a look then. Thanks.

The problem is not reproduced locally, nor does deploying to Azure directly with the [Azure Functions maven plugin](https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Functions).

As far as I can see, the problem is that when deploying in [.zip format](https://learn.microsoft.com/en-us/azure/azure-functions/deployment-zip-push#cli) with the Azure **CLI**, the `MAIN_CLASS` environment variable is not automatically created in the function configuration.  

However, deploying in Azure with the [Azure Functions maven plugin](https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Functions) does create it automatically:

![image](https://user-images.githubusercontent.com/9643385/214038346-4f244471-82ef-4f5b-b8c0-b6cc5be102a3.png)


All this would not affect if in the manifest of the generated .jar it had the `MAIN_CLASS` attribute instead of `Main-Class`:
![image](https://user-images.githubusercontent.com/9643385/214038882-ba39b6fd-3790-4304-a7bc-852ae0b0e16c.png)

**Comment by kaibocai** [comment]
Hi @ferblaca , few things we should be clear about
1. If you want to add a appsetting when you deploy through azure function maven plugin or azure cli, it's set by you. When you deploy from azure function maven plugin, you are possibly add the appsetting in your pom file, for example: https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Functions:-Configuration-Details
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/89094811/214145749-db219228-9646-4959-9a60-03cd5365d101.png">

When you deploy from azure cli, I am not sure if we have an option to add appsetting during the deployment, but you can use this command https://learn.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest to config your appsetting once you have function app created. 

2. I don't think appsetting `MAIN_CLASS` is needed. I am referring to spring cloud function example at https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-azure, I deployed to azure and everything works fine for me. I don't have appsetting `MAIN_CLASS`. 
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/89094811/214146675-53c1ed71-cac7-4927-9519-0c373d7a3d82.png">
<img width="709" alt="image" src="https://user-images.githubusercontent.com/89094811/214146834-c18cf1fb-5f3b-4666-a584-a936ec267fe8.png">

I am spring-cloud-function-dependencies 4.0.0-SNAPSHOT, please check your version. Thanks.

**Comment by jdubois** [comment]
@msftbot please keep this opened

**Comment by sergey124** [comment]
Seems like azure-functions-java still doesn't add `MAIN_CLASS` to `MANIFEST.MF`

**Comment by kaibocai** [comment]
> Please reopen, the azure-functions-java still doesn't add `MAIN_CLASS` to `MANIFEST.MF`

Can you share the code? Ensure you are using the latest spring function dependency, they have already updated this logic. azure-function-java should never operate customers' `MAINFEST.MF` file.

**Comment by sergey124** [comment]
@kaibocai , thanks, you're right, with latest dependencies it works if specify 
- `MAIN_CLASS` in `local.settings.json`
- `MAIN_CLASS` in `src/main/azure/local.settings.json`
- `start-class` in `pom.xml`

[Made a sample project with that](https://github.com/sergey124/azure-function-example-spring-maven)
