### ISSUE TITLE
Worker dependencies must be shaded (package renamed) to avoid dependency collision 

### ISSUE THREAD

**Issue by Tetradeus** [Azure/azure-functions-java-worker#340]
Looking at this https://github.com/Azure/azure-functions-java-worker/wiki/Azure-Java-Functions-Worker-Dependencies, couldn't you shade common libraries in order to avoid dependency collision and runtime issue ?

I am talking about guava, netty, apache commons, ...

Right now, it is very difficult to understand why a function is failing when it happens.

I tried to use azure storage java sdk v 12.1.0 (last version) and because of a collision with netty it just could not work (Luckily the sdk provides a way to also use the okhttp client else I would have been stuck)

**Comment by amamounelsayed** [comment]
@Tetradeus  We are working on shading the netty jar in the next release. We will be working on the next libraries next.
