### ISSUE TITLE
Support for preferredLocations in Cosmos DB (multi master) Input binding

### ISSUE THREAD

**Issue by kulkarnisonia16** [Azure/azure-functions-java-worker#344]
Supported for C# - https://medium.com/microsoftazure/azure-cosmos-db-functions-cookbook-multi-master-preferred-region-ac1f7c5d1d31

**Comment by kamperiadis** [comment]
According to the documentation [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-trigger?tabs=in-process%2Cfunctionsv2&pivots=programming-language-java) this is already supported.
