### ISSUE TITLE
Refactor DefaultClassLoaderProvider

### ISSUE THREAD

**Issue by mnriem** [Azure/azure-functions-java-worker#348]
Please consider refactoring src/main/java/com/microsoft/azure/functions/worker/reflect/DefaultClassLoaderProvider.java as the getClassLoader method has a side effect as it calls setContextClassLoader on the thread. 

This really should be done in a try/finally block where the class loader is being used.

Sequences of events should be.

1. Capture the original context class loader of the thread
2. In the try block
  a) Call getClassLoader
  b) Set the new context class loader on the thread
  c) Execute business logic (the function)
3. In the finally block associated with the above try
  a) Restore the original context class loader of the thread

**Comment by kulkarnisonia16** [comment]
Thanks for your suggestion, will have a look.

**Comment by amamounelsayed** [comment]
Got fixed by, https://github.com/Azure/azure-functions-java-worker/pull/361
Always thank you @mnriem
