### ISSUE TITLE
Access Azure SQL 

### ISSUE THREAD

**Issue by vishalkothari** [Azure/azure-functions-java-worker#35]
I am trying to access Azure SQL from Azure functions. To do the same I have added this dependency in in pom.xml
```
<dependency>
 <groupId>com.microsoft.sqlserver</groupId>
 <artifactId>mssql-jdbc</artifactId>
 <version>6.2.2.jre8</version>
 <type>jar</type>
</dependency>
 
```

To access the Azure SQL using JDBC, I am using
```
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
Connection conn = DriverManager.getConnection(connectionString);
```
The test case execution during mvn package works fine and I get the connection.
But during mvn azure-functions:run, I get ClassNotFoundException for com.microsoft.sqlserver.jdbc.SQLServerDriver. 

Can you please let me know how to add the SQL Server jar file to Azure function package?

Regards,
Vishal Kothari

**Comment by JunyiYi** [comment]
To use any 3rd party libraries, you need to make a **fat JAR** using the following plugin in your POM.xml:
```xml
      <plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                  </excludes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by nicenemo** [comment]
Thanks for clarifying this JunyYi. After solving https://github.com/Microsoft/azure-maven-plugins/issues/61.
I have a similar experience.  My code runs in integration test but it freezes when running as a service locally. No exception is thrown.
My context:
* Multi module project
* Several own libraries with no or only "java.*" dependencies.
* 2 PDFBox jars
* 3 Bouncy castle jars
* Dependencies needed for Azure Keyvault.

It does not freeze on bundled own libraries.
Explicitly bundeling the specific BouncyCastle PDFBox and Azure Keyvault jars gives a weird runtime error.
Above you use *:* . I will try that today (CET timezone.)

**Comment by nicenemo** [comment]
Suggestion: https://github.com/JunyiYi work together with https://github.com/xscript to get the docs and samples improved.

**Comment by nicenemo** [comment]
Shade plugin does not work with signed jars such as Bouncy Castle.

**Comment by JunyiYi** [comment]
Have you tried the code snippet I provided before? I've already excluded all signatures.

**Comment by JonathanGiles** [comment]
I am running into the same issue too. My code freezes when trying to bring in a JDBC driver or JPA provider. I tried the advice above but at runtime I get `java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver`. This occurs when I run `mvn clean package azure-functions:run`. Any pointers would be appreciated!

**Comment by JonathanGiles** [comment]
Attaching simple test application that demonstrates the issue. Please let me know if I'm misunderstanding something!

[externaljarbug.zip](https://github.com/Azure/azure-functions-java-worker/files/1599680/externaljarbug.zip)

**Comment by JonathanGiles** [comment]
I have tried to use the shade plugin in the linked zip above, but to no avail - I still see the runtime exception - it for some reason can not find the relevant classes, despite being in the jar.

**Comment by JonathanGiles** [comment]
Can someone review the code I attached two comments above to clarify how to resolve / work around this issue? For me right now it is a blocker on continued use of Azure Functions. Thanks.

**Comment by JunyiYi** [comment]
Hi @JonathanGiles , please try the following two steps:

- Put `maven-shade-plugin` before `azure-functions-maven-plugin`. *You can confirm the correct behavior by checking the size of `target/azure-functions/externaljarbug-20180103203937689/externaljarbug-1.0-SNAPSHOT.jar`, it should be at least several hundreds KB instead of less than 10 KB*
- Update the runtime `azure-functions-core-tools@core` to the latest version. *You can confirm that by comparing the version number printed out when you run your function: `Microsoft Azure Functions Java Runtime [build 1.0.0-beta-2]`*

And P.S., this is already a **CLOSED** issue, please create new one for additional questions.

**Comment by JonathanGiles** [comment]
Your first bullet point was the relevant one for me - the ordering of the plugins is important! The documentation should be updated to clarify this. Thanks!
