### ISSUE TITLE
Event Grid output binding does not work on Java

### ISSUE THREAD

**Issue by johndowns** [Azure/azure-functions-java-worker#355]
In the process of updating the [documentation for the Event Grid output binding](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid) (see [this PR](https://github.com/MicrosoftDocs/azure-docs-pr/pull/103060)), I discovered that the output binding does not work correctly with Java functions. It does work correctly for .NET and Node.js. (Note I have opened a [separate issue to log that this doesn't work for Python either](https://github.com/Azure/azure-functions-python-worker/issues/638).)

* I wasn't able to get a test function working for the Event Grid output binding. I can see the trigger binding works - this problem is specifically about the output binding.
* However I can see that for the trigger, there is [a Java annotation](https://github.com/Azure/azure-functions-java-library/blob/master/src/main/java/com/microsoft/azure/functions/annotation/EventGridTrigger.java) in the Azure Functions Java library, so I assume something similar would be needed here too.
* Also, [as documented on the Python issue](https://github.com/Azure/azure-functions-python-worker/issues/638) the bundle looks like it hasn't been updated to include the Event Grid output binding.

**Comment by shreyas-gopalakrishna** [comment]
This is currently fixed in the java library. Closing it for now
