### ISSUE TITLE
Memory leak in the Java SDK for blob storage

### ISSUE THREAD

**Issue by kulkarnisonia16** [Azure/azure-functions-java-worker#356]
This is using the new v3 API for blob storage. Doing a "blobContainerClient.listBlobs().streamByPage()" is causing memory leaks when you have a huge number of blobs.

Here is the solution, that indeed works in production:
- use `streamByPage` and not `iterableByPage`, as it has a `close` method
- force clean the body of HTTP requests using the Reactor API, using `response.getRequest().setBody(Flux.never());`
- disable the buffer copies in Netty: `new NettyAsyncHttpClientBuilder().disableBufferCopy(true).build();`

**Comment by alzimmermsft** [comment]
This looks similar to an issue reporting in `azure-sdk-for-java` which is actively being looked at and has a possible fix. https://github.com/Azure/azure-sdk-for-java/issues/12453

**Comment by amamounelsayed** [comment]
Thank you @alzimmermsft
