### ISSUE TITLE
JVM heap size cannot be configured in Azure Functions

### ISSUE THREAD

**Issue by kulkarnisonia16** [Azure/azure-functions-java-worker#357]
Customer needs to put a huge heap size (10 Gb) for an Azure Function for Java.
He's using a Premium P3V2.
He is trying to force the heap size using the standard "JAVA_OPTS" environment variable (he's setting it to "-Xmx10g -Xms10g".
But when he monitors his application (using Spring Boot micrometer), those parameters are not working - he stays with a "small" JVM (2 Gb) and gets out of memory errors.

**Comment by JeryLu2020** [comment]
Same ask here

**Comment by sschmeck** [comment]
It seems working using `JAVA_OPTS`.

```Java
// Operating System: Windows
// App Service Plan: <custom name> (EP1: 1)
// Configuration -> JAVA_OPTS="-Xmx3072m -Xms3072m"
// ...

public class CustomClass {
    // ... 
    @FunctionName("custom-function")
    public void run(/* ... */ final ExecutionContext context) {
        Logger logger = context.getLogger();
        RuntimeMXBean runtimeMxBean = ManagementFactory.getRuntimeMXBean();
        String jvmOpts = String.join(", ", runtimeMxBean.getInputArguments());
        logger.info(String.format("JVM options - %s.", jvmOpts));

        Runtime rt = Runtime.getRuntime();
        String heapSpace = String.format("max: %d, free: %d, total: %d", rt.maxMemory(), rt.freeMemory(), rt.totalMemory());
        logger.info(String.format("Heap space - %s.", heapSpace));
        context.getLogger().info(String.format("Received event: %s", event));
    }
}
```
The code above produced the following Application Insights logs.
```
JVM options - -XX:+TieredCompilation, -XX:TieredStopAtLevel=1, -Xverify:none, -Djava.net.preferIPv4Stack=true, -Xmx3072m, -Xms3072m.
Heap space - max: 3113877504, free: 2443986656, total: 3113877504.
```

**Comment by amamounelsayed** [comment]
Thank you @sschmeck, you are correct it should be working. I tested with linux and it worked too. 

Please can you share your sku, and in case you are still facing the same issue?

**Comment by toyip-fadv** [comment]
same issue, we have tried it, no effect.  Where did you add the JAVA_OPTS (the app setting) right?

**Comment by kaibocai** [comment]
@tyipfadv please checkout this link https://github.com/Azure/azure-functions-java-worker/wiki/How-to-customize-JVM-options-on-Azure-Functions. thanks.

**Comment by toyip-fadv** [comment]
the link showed how to do other JVM options, I used -X instead for memory setting.  Here is the app setting from the portal, no effect.  restart, redeploy, stop/start... nothing.  Am I missing something?

<img width="444" alt="Screenshot 2023-01-18 at 3 42 46 PM" src="https://user-images.githubusercontent.com/80072903/213290366-fd911def-9264-4292-aa10-d50a693da160.png">

**Comment by kaibocai** [comment]
-Xmx is also JVM options. 

Use corresponding appsetting for consumption plan just as the link shows. Thanks. 
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/89094811/213290999-05431854-9d69-43e5-b140-f56cb3ae1829.png">

**Comment by toyip-fadv** [comment]
So, can you tell me how to set the -Xmx?  do we need to use -D?
