### ISSUE TITLE
Feature Request: ServiceBusTopicTrigger

### ISSUE THREAD

**Issue by kevinhillinger** [Azure/azure-functions-java-worker#36]
Checking beta2 in azure, here is my function and config:

```
package com.hillingk;

import com.microsoft.azure.serverless.functions.annotation.*;
import com.microsoft.azure.serverless.functions.*;

/**
 * Azure Functions with HTTP Trigger.
 */
public class Function {

    @FunctionName("hello")
    public void hello(@ServiceBusTopicTrigger(name = "message", topicName = "hello", 
         connection = "servicebusconnection", subscriptionName = "world") String message,
                                     final ExecutionContext context) {
        context.getLogger().info(message);
    }
}
```

Configuration:
```
{
  "scriptFile" : "..\\functions-beta2-1.0-SNAPSHOT.jar",
  "entryPoint" : "com.hillingk.Function.hello",
  "bindings" : [ {
    "type" : "serviceBusTrigger",
    "name" : "serviceBusTrigger",
    "direction" : "in",
    "topicName" : "hello",
    "subscriptionName" : "world",
    "connection" : "servicebusconnection",
    "access" : "MANAGE"
  } ],
  "disabled" : false
}
```

The error message

> Error:
> 
> Function ($hello) Error: The binding type 'serviceBusTrigger' is not registered. Please ensure the type is correct and the binding extension is installed.
> Session Id: 02247ada41494083b798465a1ca7bfe6
> 
> Timestamp: 2017-11-28T21:29:11.950Z

**Comment by JunyiYi** [comment]
Service Bus is not supported for now. It will be enabled later with extensions.

**Comment by kevinhillinger** [comment]
@JunyiYi as it stands, can you confirm the similar timeline as mentioned in #28 for ServiceBusQueueTrigger and ServiceBusTopicTrigger?

**Comment by JunyiYi** [comment]
Service Bus is enabled through extensions internally. 
* Add feed https://www.myget.org/F/azure-appservice/api/v3/index.json to your NuGet global configuration (through Visual Studio or command line)
* Using `func extensions install --package Microsoft.Azure.WebJobs.ServiceBus --version 3.0.0-beta4-11131` to install it.

**Comment by kevinhillinger** [comment]
Cross reference: [azure-webjobs-sdk/1329](https://github.com/Azure/azure-webjobs-sdk/issues/1329)

**Comment by paulbatum** [comment]
Closing this as its supported. There might still be pending template updates to make this functionality obvious.
