### ISSUE TITLE
Raw Response/Request

### ISSUE THREAD

**Issue by bbilger** [Azure/azure-functions-java-worker#37]
(follow-up: https://github.com/Azure/azure-functions-java-worker/issues/16#issuecomment-345861061)

How can I return a string (or byte array) left untouched?

```java
@FunctionName("hello")
public HttpResponseMessage<String> hello(@HttpTrigger(name = "req", methods = {"get", "post"}, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<String> req, ExecutionContext context) {
  context.getLogger().info("started");
  context.getLogger().info(req.getBody());
  HttpResponseMessage<String> response = req.createResponse(200, "{\"test\": \"test\"}");
  response.addHeader("Content-Type", "application/json");
  return response;
}
```

`curl -v -H "Accept: application/json" http://localhost:7071/api/hello`
returns `"{\"test\": \"test\"}"` instead of `{"test": "test"}`

`curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:7071/api/hello`
logs (looks like it was de-serialized and re-serialized)
```
{
  "key1": "value1",
  "key2": "value2"
}
```

`curl -d '{"broken' -H "Content-Type: application/json" -X POST http://localhost:7071/api/hello`
crashes (which kind of proves that it's not passed as is)

**Comment by JunyiYi** [comment]
**For the first question** Azure Function is a strongly typed system, your response is of type String, so it will escape your return value into a String. If you want to return a JSON object, then you should return a POJO. Don't mix them together and try to add the headers by yourself, let the runtime do it. Here is the modified sample:
```java
public class Http {
    @FunctionName("hello")
    public HttpResponseMessage<Model> hello(@HttpTrigger(name = "req", methods = {"get", "post"}, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<String> req, ExecutionContext context) {
      context.getLogger().info("started");
      context.getLogger().info(req.getBody());
      return req.createResponse(200, new Model("test"));
    }

    public static class Model {
        Model(String content) { this.test = content; }
        private String test;
    }
}
```

**For the second question** It is a known issue in the Azure Functions runtime and we will fix it.

**Comment by bbilger** [comment]
@JunyiYi 
I understand the intention but what if I want to
a) take care of (de-) serialization myself; e.g. use some other framework or customize the process (in case of Jackson set/unset some features)?
b) return/consume some binary data?

If I am allowed to compare Azure to AWS, here: AWS lambda started strongly typed, as well. By popular demand, however, lambda-proxy integration was introduced which - amongst other things - allows to handle the cases above.

And to be more concrete about my particular use-case: I'd love add support for Azure (functions) in my framework [JRestless](https://github.com/bbilger/jrestless) which allows to use JAX-RS in serverless environments.

**Comment by JunyiYi** [comment]
byte[] could be used to handle binary data.
And we strongly recommend you to use standard types (Java primitives, POJOs, byte[]) rather than wrapping stuffs in a String. Of course you can do your own parsing logic internally, but make sure all Input/output binding types are standard.
Similar concepts compared to AWS lambda-proxy is not available here. So please keep the best practice of Azure Functions, which will also help your logic become clearer.

**Comment by bbilger** [comment]
That's a bit disappointing. I am sure I am not the only one who would love to see this feature in Azure functions but okay.

**Comment by christopheranderson** [comment]
I do have a flag that we use in JS to specify that we shouldn't do any additional processing of the returned content in our HTTP handler. This rolled out for Node.js in the last release. We can discuss how this feature would work in Java.

**Comment by bbilger** [comment]
This sounds good.
Any chance something similar could be introduced for requests, as well (not only for Java)? 
If I am not wrong, then in case of C# this is possible, as well: `HttpRequestMessage.Content.ReadAsStringAsync`, no?

**Comment by JunyiYi** [comment]
[Azure functions host](https://github.com/Azure/azure-functions-host) will change the behavior (https://github.com/Azure/azure-functions-host/issues/2552) regarding this, and Java worker will be updated accordingly.

**Comment by pragnagopa** [comment]
Closing as resolved. Please reopen if this is still an issue
