### ISSUE TITLE
Creating CosmosDB client freezes the function

### ISSUE THREAD

**Issue by syedhassaanahmed** [Azure/azure-functions-java-worker#38]
We're building a Java HTTP trigger function following [this doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven) and trying to insert into `Cosmos DB` Collection. Cosmos DB SDK have been correctly packaged as `maven` dependency.

```xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-documentdb</artifactId>
    <version>1.9.1</version>
</dependency>
```

However the call to create `DocumentClient` just freezes the function (both locally as well as in Azure). Same code works fine inside a regular Java Console app. Here is what we're doing

```java
package com.fabrikam.functions;

import java.util.*;
import com.microsoft.azure.serverless.functions.annotation.*;
import com.microsoft.azure.serverless.functions.*;

import com.microsoft.azure.documentdb.ConnectionPolicy;
import com.microsoft.azure.documentdb.ConsistencyLevel;
import com.microsoft.azure.documentdb.DocumentClient;

public class Function {

        private DocumentClient client;

        @FunctionName("hello")
        public HttpResponseMessage<String> hello (
                @HttpTrigger(name = "req", methods = {"get", "post"}, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<Optional<String>> request,
                final ExecutionContext context) {
                context.getLogger().info("Function started.");

                this.client = new DocumentClient("https://FILLME.documents.azure.com",
                        "FILLME",
                        new ConnectionPolicy(),
                        ConsistencyLevel.Session);

                context.getLogger().info("Function ended.");

                return request.createResponse(200, "Hello, Cosmos DB!");
        }
}
```
 
Log of above execution says "Function started."

**Comment by nicenemo** [comment]
According to the answer of a support ticket we had in a project.
You have to create a fat jar with all dependencies in it. This can be done with the shade plugin.

Also the functions project should not be part of a multi module project.
The following Shade configuration works for us.
```XML
     plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <transformers>
                        <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                            <mainClass>com.example.functions:Function</mainClass>
                        </transformer>
                        <!-- transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"></transformer -->
                    </transformers>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
            </plugin>
```

**Comment by christopheranderson** [comment]
@JunyiYi - should the Java Functions tooling do this automatically? It seems like a common scenario.

**Comment by JunyiYi** [comment]
Yes. We have updated the archetype to automatically include a FAT-JAR plugin.

**Comment by syedhassaanahmed** [comment]
@JunyiYi Is the FAT-JAR archetype version published to Maven?

**Comment by pragnagopa** [comment]
@JunyiYi - Can you please follow up and close this issue if it's addressed?

**Comment by JunyiYi** [comment]
Hi @syedhassaanahmed , we have deprecated the "FAT-JAR" solution for dependencies. And we introduced a more stable and fluent experience of ["lib/" folder dependencies](https://github.com/Azure/azure-functions-java-worker#2-dependencies-in-the-lib-folder).

Can you confirm whether your problem is solved by leverage this solution?

**Comment by syedhassaanahmed** [comment]
Hi @JunyiYi I've tried the lib folder solution and I can see the dependencies are correctly copied to `<artifactId>/target/azure-functions/<appName>/lib`, however the function still freezes as described in issue description.

**Comment by JonathanGiles** [comment]
@syedhassaanahmed Please refer to the comment in https://github.com/Azure/azure-functions-java-worker/issues/53 - there might be some advice in there that you can leverage.

**Comment by plasne** [comment]
@syedhassaanahmed Make sure you also added:

```
<properties>
		...
    <functionLib>${project.build.directory}/azure-functions/${functionAppName}/lib</functionLib>
</properties>bash
```

**Comment by JonathanGiles** [comment]
@plasne This advice does not appear to be on the main readme.md file. I note you probably saw this advice in @kevinhillinger repo here: https://github.com/kevinhillinger/azure-functions-samples/tree/master/java/slf4j ?

I just created a PR to remove the old shade advice, but I suspect this PR should be updated to include this advice too, which I will do now.

**Comment by JonathanGiles** [comment]
I've updated the PR here: https://github.com/Azure/azure-functions-java-worker/pull/78

However, I hope that soon the advice will no longer be needed as the archetype will simply generate this by default (@JunyiYi?)

**Comment by syedhassaanahmed** [comment]
@JonathanGiles Thanks for the hint. Current archetype is generating this which should be enough right?
```xml
<outputDirectory>${project.build.directory}/azure-functions/${functionAppName}/lib</outputDirectory>
```

@JunyiYi I can confirm the issue is resolved after updating the functions core tools.

**Comment by JunyiYi** [comment]
@JonathanGiles , I believe [the archetype](https://github.com/Microsoft/azure-maven-archetypes/blob/master/azure-functions-archetype/src/main/resources/archetype-resources/pom.xml#L138) has already been updated.

**Comment by JunyiYi** [comment]
Thanks @syedhassaanahmed for the confirmation.
