### ISSUE TITLE
Azure Functions Java Worker 1.7.1 -- Dependencies change opt in

### ISSUE THREAD

**Issue by amamounelsayed** [Azure/azure-functions-java-worker#381]
This release is for shading all worker jars. This will give the option to clients to override the current behavior for how java worker jars are load it.

Background, before this release azure functions worker dependence takes precedence over the customer code dependencies in case they use the same ones. The current work is to give a way to customer dependencies to takes higher precedence by loading it first.

Only for JAVA 8
To be a backward compatible We freeze all the jars we currently have added to lib_worker_1.6.2.
We still load the worker jars first then the client jars.

If the client like to reverse this order and their jars takes presence first, they will need to add FUNCTIONS_WORKER_JAVA_LOAD_APP_LIBS True or 1. By this way it will be opt-in and load their jars first then worker jars.

JAVA 11 will use only the customer jars no need to add any application settings.

This will make java functions compatible with the latest spring and java azure sdks.

Fixes #340, Fixes #183, Fixes #373, Fixes #368, Fixes #365, Fixes #341

Releases contain the enhancement, 
v3 3.0.14251 or higher
v2 2.0.14248 or higher.

Core tools,
v3 3.0.2852 or higher
v2  2.7.2855 or higher

Windows deployment done.
Linux consumption deployment done.
Linux dedicated/premium, deployment done.
Core tools, released.

**Comment by jongio** [comment]
@anirudhgarg @TsuyoshiUshio - Could you please provide an update on this?  Would be great to get it addressed as we have stale related issues that are dependent on this fix.  Thanks, Jon

**Comment by amamounelsayed** [comment]
@jongio Thank you so much, We updated the status of the deployment. Please let us know if you have any questions.

**Comment by amamounelsayed** [comment]
**Releases contain the enhancement,**
v3 3.0.14251 or higher
v2 2.0.14248 or higher.

**Windows** deployment done.
**Linux consumption** deployment done.
**Linux dedicated/premium**, still deploying.

**Comment by jongio** [comment]
@g2vinay - Please have a look at previous comment and see if we can resolve ours with the current deployment.

**Comment by amamounelsayed** [comment]
Releases contain the enhancement,
v3 3.0.14251 or higher
v2 2.0.14248 or higher.

Windows deployment done.
Linux consumption deployment done.
Linux dedicated/premium, deployment done.

**Comment by amamounelsayed** [comment]
This fix is not released yet by core tools, it will be released in the next one.
If user face this issue locally this may be the reason. We will update the issue once coretools get released.

Linux and windows all skus runtime in Azure cloud has been released.

**Comment by kashyap-bhatt-by** [comment]
> @amamounelsayed 
> 
> This fix is not released yet by coretools, it will be released in the next release.
> If user face this issue locally this may be the reason. We will update the issue once coretools get released.
> 
> Linux and windows all skus runtime in Azure cloud has been released.

How can I follow delivery of this fix? Is there some way I can watch some issue/repo/something so I get an email when this is released?

**Comment by amamounelsayed** [comment]
> > @amamounelsayed
> > This fix is not released yet by coretools, it will be released in the next release.
> > If user face this issue locally this may be the reason. We will update the issue once coretools get released.
> > Linux and windows all skus runtime in Azure cloud has been released.
> 
> How can I follow delivery of this fix? Is there some way I can watch some issue/repo/something so I get an email when this is released?

Thank you so much @kashyap-bhatt-by for your message, you can keep track of the coretools releases at https://github.com/Azure/azure-functions-core-tools/releases

**Comment by amamounelsayed** [comment]
Core tools have been release 
v3 3.0.2852 or higher
v2  2.7.2855 or higher

https://github.com/Azure/azure-functions-core-tools/releases
