### ISSUE TITLE
Use WORKER_DIRECTORY from WorkerInitRequest

### ISSUE THREAD

**Issue by amamounelsayed** [Azure/azure-functions-java-worker#392]
https://github.com/Azure/azure-functions-host/issues/6427

**Comment by pragnagopa** [comment]
See PR: https://github.com/Azure/azure-functions-language-worker-protobuf/pull/48

**Comment by amamounelsayed** [comment]
https://github.com/Azure/azure-functions-language-worker-protobuf/pull/48#event-3622554315
https://github.com/Azure/azure-functions-host/pull/6441#pullrequestreview-461082446
