### ISSUE TITLE
Cannot retrieve JFR results of Java Worker in Linux.

### ISSUE THREAD

**Issue by YusukeTobo** [Azure/azure-functions-java-worker#408]
#### Investigative information

- Container Repository: mcr.microsoft.com/azure-functions/java:3.0-java11-appservice-stage6 
- Region: Japan East
- Java Version:  8 and 11

#### Repro steps

1. make webssh to the container which hosts the java worker via Kudu.
2. find the worker PID using the following command.
```bash
/usr/lib/jvm/zre-11-azure-amd64/bin/jcmd
```
3.  run jcmd to invoke Java Flight Recorder.
```bash
/usr/lib/jvm/zre-11-azure-amd64/bin/jcmd <PID> JFR.start name=MyRecording settings=profile duration=30s filename="test.jfr"
```

#### Expected behavior

/home/wwwroot/test.jfr would be created.

#### Actual behavior

```
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/42/root/tmp/.java_pid42: target process 42 doesn't respond within 10500ms or HotSpot VM not loaded
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(Unknown Source)
        at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(Unknown Source)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(Unknown Source)
        at jdk.jcmd/sun.tools.jcmd.JCmd.executeCommandForPid(Unknown Source)
        at jdk.jcmd/sun.tools.jcmd.JCmd.main(Unknown Source)
```

#### Known workarounds

I found that we can retrieve the JFR result when we have the following Application Settings.
``` JAVA_OPTS = -XX:+StartAttachListener```

#### Impact of this issue

It would be hard to find out performance bottleneck in Linux if we don't have an option to utilize JFR and jcmd.

**Comment by TsuyoshiUshio** [comment]
We can reproduce the issue, and also the workarounds works. It might take some time to investigate more. Until then, could you keep the workaround?

**Comment by YusukeTobo** [comment]
Thank you for trying to reproduce it out. Until you'll fix this issue, we'd keep the workaround.

**Comment by georgeOsdDev** [comment]
Is there any update on this issue?
I could save jfr without workaround(`JAVA_OPTS = -XX:+StartAttachListener`)  today.

LinuxFxVersion "Java|8"
<img width="700" alt="image" src="https://user-images.githubusercontent.com/1381907/215653765-d1ad2db9-1e0e-4497-85a3-8064de0b80d9.png">

**Comment by georgeOsdDev** [comment]
`java|11` also works without workaround.

**Comment by shreyas-gopalakrishna** [comment]
Given the workaround is no longer needed, will be closing this issue. Please reopen if any more support is needed

**Comment by georgeOsdDev** [comment]
Hi @shreyas-gopalakrishna 
workaround is still needed for Java|17 today. Could you repopen the issue?

![image](https://github.com/user-attachments/assets/7c2214ae-e161-4be8-bf54-e1587a6f2048)

After adding `JAVA_OPTS = -XX:+StartAttachListener`
![image](https://github.com/user-attachments/assets/f2f6249e-e91f-48c9-81fd-e94c32785788)
