### ISSUE TITLE
createResponse method on HttpResponseMessage inconvenient when no body required

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-functions-java-worker#41]
The HttpRequestMessage class has a `createResponse(status, body)` method to return a response. This seems unfortunate when no body is required, but a header is, for example in the case of a redirect.

It would possibly be useful to have a `createResponse(status)` or `createResponse()` overloaded method, such that it is not necessary to write code such as the following (where `url` is duplicated or set to null - it is unclear what best practice is):

```
HttpResponseMessage response = request.createResponse(status, url);
response.addHeader("Location", url);
return response;
```

**Comment by paulbatum** [comment]
@JunyiYi do you plan on addressing this in the near future? If so can you move to backlog milestone, otherwise put it in unknown milestone.

**Comment by paulbatum** [comment]
I see a merged PR. Going to assume this is addressed.
