### ISSUE TITLE
gson response date-format

### ISSUE THREAD

**Issue by ODH003** [Azure/azure-functions-java-worker#419]
Hi team, I'm using azure cloud function java 11 and the response of the functions are ok, just I would like to change the date-format for all output object. But I couldn't find any information about it.

![image](https://user-images.githubusercontent.com/48140216/109092639-ea45dc00-76e4-11eb-8715-247c21db8168.png)

I would like to get the response format:
spring.gson.date-format=yyyy-MM-dd'T'HH:mm:ss

Like left json of the picture.

**Comment by CrawX** [comment]
@ODH003 fyi I posted a workaround that could maybe help you out in the feature request #424.

**Comment by kaibocai** [comment]
Hi @ODH003 , Thanks very much for opening this issue. As CrawX provided a workaround, we still want to know if you can provide an repo used to reproduce this issue. Thanks very much.
