### ISSUE TITLE
'worker.config.json' configuration hardcoded for Windows

### ISSUE THREAD

**Issue by shaunthomas999** [Azure/azure-functions-java-worker#421]
Current `worker.config.json` has windows specific environment variable reference because of which `azure-functions-java-worker` won't work in macOS (also in linux)

E.g., JAVA_HOME - referenced as `%JAVA_HOME%`

#### Repro steps

* Follow instructions in https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-maven-intellij
* Worker won't startup properly while trying to run the application
 
```
Failed to start Worker Channel. Process fileName: %JAVA_HOME%/bin/java
```

#### Known workarounds

* Manually update `worker.config.json` file to have `$JAVA_HOME` instead of `%JAVA_HOME%`
* Ref: https://stackoverflow.com/questions/64032219/azure-function-in-java-does-not-work-locally

**Comment by amamounelsayed** [comment]
Thank you so much for reporting this issue.

**Comment by shaunthomas999** [comment]
Actually, change `%JAVA_HOME%` to `$JAVA_HOME` didn't work for me eventually. I had to give full path to the java executable to make it work.

**Comment by shaunthomas999** [comment]
@amamounelsayed - Any idea when this issue will be fixed?

**Comment by brunoborges** [comment]
Can we change the title of this issue to `worker.config.json configuration hardcoded for Windows`?

Because this is preventing the worker from running on Linux and WSL (Windows Subsystem for Linux) besides macOS.
