### ISSUE TITLE
FUNCTIONS_WORKER_JAVA_LOAD_APP_LIBS seems no effect on local run (works on functions)

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-functions-java-worker#425]
FUNCTIONS_WORKER_JAVA_LOAD_APP_LIBS works fine on functions but not for local development:

The following sample can be used to reproduce this issue:

[hello-spring-function-azure.zip](https://github.com/Azure/azure-functions-java-worker/files/6192909/hello-spring-function-azure.zip)

run locally - "mvn azure-functions:run", and hit the endpoint, worker fails with dependency conflicts.

> Exception: NoSuchMethodError: io.netty.handler.ssl.SslProvider.isAlpnSupported(Lio/netty/handler/ssl/SslProvider;)Z
Stack: java.lang.reflect.InvocationTargetException
[2021-03-10T22:31:22.716Z] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-03-10T22:31:22.716Z] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-03-10T22:31:22.716Z] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-03-10T22:31:22.716Z] at java.lang.reflect.Method.invoke(Method.java:498)
[2021-03-10T22:31:22.716Z] at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)

**Comment by amamounelsayed** [comment]
Can you please share your core tools versions? And your java worker version.

**Comment by anuchandy** [comment]
sure, here is what copied from the log output of "mvn azure-functions:run"

> Azure Functions Core Tools (3.0.2534 Commit hash: bc1e9efa8fa78dd1a138dd1ac1ebef97aac8d78e)
Function Runtime Version: 3.0.13353.0
Azure Functions Java Worker  version [ 1.5.2-SNAPSHOT]

**Comment by amamounelsayed** [comment]
Thank your for your message, You need to upgrade to the newer core tools 
https://github.com/Azure/azure-functions-java-worker/issues/381

**Comment by saikirangit** [comment]
@anuchandy @amamounelsayed  Thank you so much. Upgrading to newer core tools resolved the issue.

**Comment by amamounelsayed** [comment]
Glad to hear, please let us know if you have any questions
