### ISSUE TITLE
Method not found returned for Java HttpTrigger with binary data

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-java-worker#44]
_From @jeffhollan on December 2, 2017 4:19_

Can't seem to find a way to successfully pass in binary data to Java function with HttpTrigger. Always says no method signature found regardless of combinations.

**Repro Steps**
1. Create Function app using Maven tools for Java
2. Add the `datatype = "binary"` attribute for the HttpTrigger and change the type to `Byte[]`, `byte[]`, or `HttpRequestMessage<byte[]>`
3. Make sure method is valid and try to return any type
4. AFter running and executing the script errors with method not found

**Other notes**
Verified that the function.json file being generated looks accurate.  Samples below:

function.json
```
{
  "scriptFile" : "../helloworld2-1.0-SNAPSHOT.jar",
  "entryPoint" : "io.hollan.hello.Function.hello",
  "bindings" : [ {
    "type" : "httpTrigger",
    "name" : "req",
    "direction" : "in",
    "dataType" : "binary",
    "authLevel" : "anonymous",
    "methods" : [ "get", "post" ]
  }, {
    "type" : "http",
    "name" : "$return",
    "direction" : "out"
  } ],
  "disabled" : false
}
```

```java
package io.hollan.hello;

import com.microsoft.azure.serverless.functions.annotation.*;
import com.microsoft.azure.serverless.functions.*;

/**
 * Azure Functions with HTTP Trigger.
 */
public class Function {
    @FunctionName("hello")
    public String hello(@HttpTrigger(name = "req", methods = {"get", "post"}, authLevel = AuthorizationLevel.ANONYMOUS, dataType = "binary") Byte[] req,
                                     final ExecutionContext context) {
        context.getLogger().info("Java HTTP trigger processed a request.");

        return "foo";
    }
}
```

_Copied from original issue: Azure/azure-webjobs-sdk-script#2179_

**Comment by christopheranderson** [comment]
_From @JunyiYi on December 7, 2017 23:52_

This is exactly the way you could pass binary data to your HTTP trigger. But make sure your content type is `application/octet-stream`:
```
curl --request POST --header "Content-Type:application/octet-stream" --data-binary "@LICENSE.txt" http://localhost:7071/api/hello
```

**Comment by christopheranderson** [comment]
_From @paulbatum on December 13, 2017 19:55_

@jeffhollan does this work for you? Trying to understand if Junyi's reply addresses the issue.

**Comment by JunyiYi** [comment]
External user didn't respond for more than two months. So I will close the issue now.

**Comment by patriot1burke** [comment]
FYI:  This bug is still an issue.

**Comment by patriot1burke** [comment]
The original poster probably just gave up.  In my case, I want all data, even texted based data like json to be able to be sent as a byte[] array.

**Comment by patriot1burke** [comment]
I get a class cast exception if I POST json to this function:

    public HttpResponseMessage run(
            @HttpTrigger(name = "req", dataType = "binary") HttpRequestMessage<Optional<byte[]>> request,
            final ExecutionContext context)
