### ISSUE TITLE
Unable to run functions locally

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-functions-java-worker#45]
I'm not sure what has happened, but I am unable to run Azure Functions locally to test any longer. I am now presented with the following output when I run `mvn azure-functions:run`:

> [INFO] Scanning for projects...
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Azure Java Functions 1.0-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- azure-functions-maven-plugin:0.1.9:run (default-cli) @ functions-test ---
> AI: INFO 17-01-2018 12:47, 1: Configuration file has been successfully found as resource
> AI: INFO 17-01-2018 12:47, 1: Configuration file has been successfully found as resource
> [INFO] Azure Functions stage directory found at: /Users/jonathan/Code/azure/test/functions-test/target/azure-functions/functions-test-20180117124644248
> [INFO] Azure Functions Core Tools found.
> [INFO] Starting running Azure Functions...
> 
>                   %%%%%%
>                  %%%%%%
>             @   %%%%%%    @
>           @@   %%%%%%      @@
>        @@@    %%%%%%%%%%%    @@@
>      @@      %%%%%%%%%%        @@
>        @@         %%%%       @@
>          @@      %%%       @@
>            @@    %%      @@
>                 %%
>                 %
> 
> Listening on http://localhost:7071/
> Hit CTRL-C to exit...
> Object reference not set to an instance of an object.

From this point it just appears to freeze with no feedback about how to resolve this issue. The code being executed here is simply the generated code from the Java tutorial here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven

**Comment by JonathanGiles** [comment]
A reboot of my machine has resolved this issue. It appears that this is all that was needed. I'll close this issue but maybe it is worth providing additional feedback if this can be identified at runtime?

**Comment by damadei** [comment]
I've noticed this happening when the Functions runtime for C# (v1.0) was up and I tried to also bring the runtime v2 up and run my java function.
