### ISSUE TITLE
Increase Java language worker startup time out in worker.config.json

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-java-worker#459]
#### Issue description 
There are some scenarios in which the Java language worker cannot initialized within 60 seconds. For this type of scenario it would be helpful to have the ability to change the Java language worker start up time and make it greater than 60 seconds.

A possible approach could be to make this value configurable using an app setting, and if this setting is not present, use a default startup timeout.

**Comment by liliankasem** [comment]
Does this PR help with this issue at all? https://github.com/Azure/azure-functions-host/pull/7491

**Comment by kaibocai** [comment]
Close this issue as the pr provide by @liliankasem helped.
