### ISSUE TITLE
Unable to get JPA working in a fatjar azure function

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-functions-java-worker#46]
When using Azure Functions with Java, I am trying to use JPA to access a database. I have a non-JPA implementation working, but I would like to work out why the JPA implementation doesn't work. All my code is available here: https://github.com/JonathanGiles/azure-functions-java-shortcode

To test, you can simply clone the repo, and modify the DataStoreFactory class to return a JPADataStore, rather than the SQLDataStore. Once this is modified, you can run the code locally with `mvn clean package azure-functions:run`. When the server is running, you can then test by doing an HTTP post to `http://localhost:7071/api/shortcode` with a `url` query parameter of a given url, e.g. `http://www.azure.com`. 

When I do this on my machine with JPA, I get the following output:

> [17/01/18 6:12:06 AM] Function started (Id=2513c795-f074-45b4-b986-98bbcb5a8b9a)
> [17/01/18 6:12:06 AM] Executing 'Functions.shortcode' (Reason='This function was programmatically called via the host APIs.', Id=2513c795-f074-45b4-b986-98bbcb5a8b9a)
> info: Worker.Java.7d7162ec-e688-46f5-ac6f-55126621a850[0]
>       Jan 17, 2018 7:12:06 PM javax.persistence.spi.PersistenceProviderResolverHolder$DefaultPersistenceProviderResolver log
> info: Worker.Java.7d7162ec-e688-46f5-ac6f-55126621a850[0]
>       WARNING: javax.persistence.spi::No valid providers found.
> [17/01/18 6:12:06 AM] A ScriptHost error has occurred
> [17/01/18 6:12:06 AM] Exception while executing function: Functions.shortcode. System.Private.CoreLib: Result: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] Exception: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] Stack: javax.persistence.PersistenceException: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:85)
> [17/01/18 6:12:06 AM] 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.db.impls.JPADatabase.<init>(JPADatabase.java:35)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.db.DataStoreFactory.getInstance(DataStoreFactory.java:20)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.functions.ShortcodeFunction.shortcode(ShortcodeFunction.java:28)
> [17/01/18 6:12:06 AM] .
> [17/01/18 6:12:06 AM] Exception while executing function: Functions.shortcode. System.Private.CoreLib: Result: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] Exception: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] Stack: javax.persistence.PersistenceException: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:85)
> [17/01/18 6:12:06 AM] 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.db.impls.JPADatabase.<init>(JPADatabase.java:35)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.db.DataStoreFactory.getInstance(DataStoreFactory.java:20)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.functions.ShortcodeFunction.shortcode(ShortcodeFunction.java:28)
> [17/01/18 6:12:06 AM] .
> [17/01/18 6:12:06 AM] 
> [17/01/18 6:12:06 AM] Exception while executing function: Functions.shortcode
> [17/01/18 6:12:06 AM] Exception while executing function: Functions.shortcode. System.Private.CoreLib: Result: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] Exception: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] Stack: javax.persistence.PersistenceException: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:85)
> [17/01/18 6:12:06 AM] 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.db.impls.JPADatabase.<init>(JPADatabase.java:35)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.db.DataStoreFactory.getInstance(DataStoreFactory.java:20)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.functions.ShortcodeFunction.shortcode(ShortcodeFunction.java:28)
> [17/01/18 6:12:06 AM] .
> [17/01/18 6:12:06 AM] Function completed (Failure, Id=2513c795-f074-45b4-b986-98bbcb5a8b9a, Duration=345ms)
> [17/01/18 6:12:06 AM] 
> [17/01/18 6:12:06 AM] Executed 'Functions.shortcode' (Failed, Id=2513c795-f074-45b4-b986-98bbcb5a8b9a)
> [17/01/18 6:12:06 AM] System.Private.CoreLib: Exception while executing function: Functions.shortcode. System.Private.CoreLib: Result: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] Exception: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] Stack: javax.persistence.PersistenceException: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:85)
> [17/01/18 6:12:06 AM] 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.db.impls.JPADatabase.<init>(JPADatabase.java:35)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.db.DataStoreFactory.getInstance(DataStoreFactory.java:20)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.functions.ShortcodeFunction.shortcode(ShortcodeFunction.java:28)
> [17/01/18 6:12:06 AM] .
> [17/01/18 6:12:06 AM]   Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is '2513c795-f074-45b4-b986-98bbcb5a8b9a'
> [17/01/18 6:12:06 AM] System.Private.CoreLib: Exception while executing function: Functions.shortcode. System.Private.CoreLib: Result: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] Exception: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] Stack: javax.persistence.PersistenceException: No Persistence provider for EntityManager named shortcodes
> [17/01/18 6:12:06 AM] 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:85)
> [17/01/18 6:12:06 AM] 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.db.impls.JPADatabase.<init>(JPADatabase.java:35)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.db.DataStoreFactory.getInstance(DataStoreFactory.java:20)
> [17/01/18 6:12:06 AM] 	at net.jonathangiles.azure.shorturl.functions.ShortcodeFunction.shortcode(ShortcodeFunction.java:28)
> [17/01/18 6:12:06 AM] .

It is possible to run the `main` method in the JPADataStore class and see that it can communicate successfully when not running as part of Azure Functions - so I am not sure why it doesn't work under Azure Functions. I'm guessing something to do with the fat jar is not correct, but I am unable to determine what. Any insights into what Azure Functions is doing would be much appreciated, so I can get to the bottom of this! Thanks.

**Comment by kevinhillinger** [comment]
@JonathanGiles I can also confirm that this is an issue. I'm experiencing the same exception, trying to work through JPA on Azure Functions. 

I'm still trying to determine root cause, but right now, the initial thought is there's an issue with the way the jar is being loaded. `createEntityManagerFactory` uses a [reflection based lookup](http://grepcode.com/file/repo1.maven.org/maven2/javax.persistence/persistence-api/1.0/javax/persistence/Persistence.java) for all providers to get persistence hooked up, and null provider throws the exception.

**Comment by JonathanGiles** [comment]
The ideal situation from my perspective would be to not require the creation of a fat jar in the first place. Ideally the azure functions tooling would simply upload all required jar files (either through maven dependency resolution or simply some convention - a file list, etc), and on azure these files will then be added to the class path as per usual. This would avoid this whole class of issue entirely.

**Comment by nicenemo** [comment]
We would like to have a package(zip) option to be able to deploy the Java functions alongside JavaScript functions using Ansible with ARM templates. I added the assemble plugin to zip the package output myself to get what we want. The azure functions plugin does zip & deploy but has no separate zip option.

Currently busy configuring the app name from outside the pom.

**Comment by kevinhillinger** [comment]
Along the same lines as @JonathanGiles , since we're running the Function App from within the same host instance (the same process), we specify a "root" lib folder that the WebJobs host can include in the classpath during the invocation of the java-worker. This is a general convention in the Java community.

The structure would be:
```
+/ [function app root]
   - /lib
        ..jar files
   - /func1
        function.json
        func1.jar
   - /func2
        function.json
        func2.jar
```

We should support both scenarios:
1. maven shade -> single jar
2. AND packaging with a zip file with separate jar dependencies.

**Comment by nicenemo** [comment]
Also not having to use a fat jar allows me to use signed jars such as the Bouncy Castle library.  I now have to use the unsigned variant Spongy Castle as a replacement. There are probably situations where that is not an option.

**Comment by kevinhillinger** [comment]
Pull request #50 submitted to resolve this issue.

**Comment by JunyiYi** [comment]
Close the issue since there are no response for more than 2 weeks.
