### ISSUE TITLE
Reading base64 encoded PNG using PDFbox fails in Azure

### ISSUE THREAD

**Issue by nicenemo** [Azure/azure-functions-java-worker#47]
High level description I have code that gets triggered by a storage queue. It then reads JSON from a blob. In this blob is a base64 encoded image. 
The blob store invents two extra Unicode character.(that will be another issue)  We strip those away. Then we decode the image and add it to a PDF using PDFBox. On the simulator and in integration tests it works on Real Azure it crashes on some PNGs in the Sun PNG decoder.

Known or should this require stacktrace and sample code?

**Comment by JunyiYi** [comment]
Providing sample code would be nice. Thanks.

**Comment by nicenemo** [comment]
Was finally two bugs on my side
1. Not correctly serializing with GSON, forgot to provide a class.
2. Off by one or more in stream copy function. Replaced by IOUtils implementation.
Strange thing was that locally using it in a test that did not use blob store or queues it worked perfect. Once you run it with queues in a function, local or remote, things broke.
