### ISSUE TITLE
Content Type text/html doesn't work for Java functions

### ISSUE THREAD

**Issue by denissp** [Azure/azure-functions-java-worker#52]
Hi

When I'm trying to execute following sample I'm getting 406 error:

    @FunctionName("test")
    public HttpResponseMessage<String> hello(
            @HttpTrigger(name = "req", methods = {"get"},
                    authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<Optional<String>> request,
            final ExecutionContext context) {

        String html = "<html><body>hello</body></html>";

        HttpResponseMessage<String> resp = request.createResponse(200, html);
        resp.addHeader("Content-Type","text/html");
        return resp;

    }

**Comment by denissp** [comment]
May be it related to https://github.com/aspnet/Mvc/issues/6657 ?

**Comment by JunyiYi** [comment]
@christopheranderson @pragnagopa , any ideas from the perspective of Host?

**Comment by kevinhillinger** [comment]
This is appears to be the same root issue as [azure-functions-host/#2339](https://github.com/Azure/azure-functions-host/issues/2339)

**Comment by pragnagopa** [comment]
Yes. this is the same issue as  [azure-functions-host/#2339](https://github.com/Azure/azure-functions-host/issues/2339)

**Comment by JunyiYi** [comment]
Tracked in host repository already. [azure-functions-host/#2339](https://github.com/Azure/azure-functions-host/issues/2339)
