### ISSUE TITLE
App Insights dynamic tracing does not work against Docker Images

### ISSUE THREAD

**Issue by purijatin** [Azure/azure-functions-java-worker#528]
#### Investigative information

This is easy to replicate. 

#### Repro steps

Usually, to enable application insights 3, we need to add the following config `ApplicationInsightsAgent_EXTENSION_VERSION=~3`. And the dynamic tracing functionality automatically works.

But if the azure function is deployed using the docker image. Then the auto-tracing does not work. To make it work, I have to manually put the agent on the classpath. 

#### Expected behavior

Either one of:

1. Adding the flag `ApplicationInsightsAgent_EXTENSION_VERSION` should make it work for Docker images as well. (Maybe the agent can be part of the parent docker image).
2. Or explicitly mention in that docs, that this functionality is only limited to `code runtime` and does not work against docker. 

#### Actual behavior

Auto tracing does not work

#### Known workarounds

Handle it manually. As shown here: https://stackoverflow.com/questions/71085054/java-azure-application-insights-dynamic-tracing-not-working-with-docker-images/71085468

#### Related information 

Provide any related information 

* Programming language used: Java

**Comment by kaibocai** [comment]
Adding @trask and @MadhuraBharadwaj-MSFT just for awareness.

**Comment by kaibocai** [comment]
@purijatin thanks for reporting this issue. We have [public review 2 of distributed tracing](https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#distributed-tracing-for-java-applications-preview) released now. In public preview 2 this issue is resovled. Thanks.
