### ISSUE TITLE
Re-enabling Application Insights does not turn on Dynamic Tracing

### ISSUE THREAD

**Issue by purijatin** [Azure/azure-functions-java-worker#529]
#### Investigative information

It is easy to replicate the bug. Have been able to replicate it several times

- Timestamp: 22nd Feb 2022
- Function App name: CodeRuntimePrac2 
- Function name(s) (as appropriate):
- Invocation ID:
- Region: centralus

Azure function deployed against Java 8 Code Runtime

#### Repro steps

Usually, to enable application insights 3, we need to add the following config ApplicationInsightsAgent_EXTENSION_VERSION=~3. And the dynamic tracing functionality automatically works.

Steps:
1. Enable dynamic tracing by adding the above flag. Goto App Insights and confirm if `Application map` is showing the graphs
![image](https://user-images.githubusercontent.com/716853/155072071-4a2dfac0-3bec-406b-b213-b401339247c9.png)

2. Now, In your azure-function portal, goto `Settings -> Application Insights` and `disable` App Insights
3. This restarts the function app. Wait for about a minute for the app to come up.
4. In your azure-function portal, goto `Settings -> Application Insights` and `enable` App Insights again

Now visit `App Insights` page and recheck `Application map`. It does not show any new map components. 

![image](https://user-images.githubusercontent.com/716853/155072560-a0dc43bd-862a-4cc2-9525-8573e686a4d5.png)

#### Expected behavior

Dynamic tracing should work if re-enabled

#### Actual behavior

It doesn't work

#### Known workarounds

I am not aware. I had to delete the function app and redeploy. 

#### Related information 

Provide any related information 

* Programming language used : Java
* Links to source: Generic. Easy for anyone to replicate

**Comment by kaibocai** [comment]
Adding @trask and @MadhuraBharadwaj-MSFT just for awareness.

**Comment by kaibocai** [comment]
@purijatin thanks for reporting this issue. We have [public review 2 of distributed tracing](https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#distributed-tracing-for-java-applications-preview) released now. Please try if this issue is resolved. I cannot reproduce this issue from myside. Thanks.
