### ISSUE TITLE
Loading Jar-files from /lib in the function app root 

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-java-worker#54]
_From @kevinhillinger on February 5, 2018 18:0_

Feature request to support jar files being loaded from a `lib` folder in function app root, so that fat jars are not required.

This is cross-referencing [this issue](https://github.com/Azure/azure-functions-java-worker/issues/48) in the azure-functions-java-worker repo.

_Copied from original issue: Azure/azure-functions-host#2382_

**Comment by dsyer** [comment]
>  fat jars are not required.

I guess it's a matter of terminology, more than anything then? To deploy a function I have to upload an archive that contains a lib folder that contains jar files. Sounds like a fat jar to me.

Could the location of the "lib" directory be configurable please? Spring Boot apps, for instance, would put them at `BOOT-INF/lib`.

**Comment by kevinhillinger** [comment]
@dsyer `lib` is a *directory* residing in the function app's root directory, not packaged in the jar.

in the [README](https://github.com/Azure/azure-functions-java-worker/blob/dev/README.md), there's a section for dependencies. The Maven plugin is copying all dependent jars (which you have control over using this plugin) to the function app's directory.

Hope that helps.

**Comment by JunyiYi** [comment]
Code has been checked in. And let me close this feature request after the changeset is published to Azure.

**Comment by JunyiYi** [comment]
Supported in #50.
