### ISSUE TITLE
Support for Java 17

### ISSUE THREAD

**Issue by onobc** [Azure/azure-functions-java-worker#548]
Some of the Azure services w/ a [managed Java runtime](https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/java-support-on-azure#supported-java-versions-and-update-schedule) are able to use Java 17. When will Azure Functions support Java 17?

**Comment by pebo** [comment]
Java 17 LTS was released just over a year ago. Are there any updates regarding if/when Azure Functions will support this version?

**Comment by kaibocai** [comment]
Java 17 will be in public review next month. Thank you.

**Comment by kaibocai** [comment]
It's now in public review. Thanks.

**Comment by MadhuraBharadwaj-MSFT** [comment]
As @kaibocai mentioned, Java 17 has been in Public Preview since Sept 28: https://azure.microsoft.com/en-us/updates/public-preview-java-17-support-in-azure-functions/

**Comment by MadhuraBharadwaj-MSFT** [comment]
We plan to announce GA support for Java 17 by mid December, 2022.

**Comment by kaibocai** [comment]
Java 17 GA was announced one month ago.

**Comment by MadhuraBharadwaj-MSFT** [comment]
https://azure.microsoft.com/en-us/updates/generally-available-azure-functions-support-for-java-17/
