### ISSUE TITLE
Document "stronger" that state between functions is separated, even for static fields!

### ISSUE THREAD

**Issue by nicenemo** [Azure/azure-functions-java-worker#57]
I Wrote a class `DataBaseMock` that mocked a database using `static` methods for CRUD.
It basically wraps a  ConcurrentHashMap<id,MySpecialRecord>.
This class works fine according to my unit tests.

When I  use the class from Azure Functions **locally**, a record inserted by one function is not observed by another function. I added logging that logs the number of entries in the map.
After inserting by one function the logging says there is one entry in the map.
The other function still logs that there are 0 entries in the map. So they cannot be the same map. Since the the methods and the map are static, I think some class loader trickery is used.

Suggestion add warning: "State is not shared between functions: not even if they are in the same class and not even if you play dirty with static fields and methods"

**Comment by kevinhillinger** [comment]
@nicenemo can you share the code you're describing so we can look into this further?

**Comment by JunyiYi** [comment]
The first sentence of [Azure Functions Java developer guide](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-java) is **Your Azure function should be a stateless class method that processes input and produces output.**

**Comment by kevinhillinger** [comment]
Junyi is correct regarding the developer guidance. I also created a sample, demonstrating a [singleton pattern implementation](https://github.com/kevinhillinger/azure-functions-samples/tree/master/azure-functions-java-designpatterns). You'll see that it leverages `synchronized`.  My guess is that even with your static methods, the code isn't taking into account the fact that Functions is going to be multi-threaded OOTB.

**Comment by Clockwork-Muse** [comment]
....and even if it did, you'd be in trouble the moment the system applied any scaling: that function is going to be spread over multiple JVMs/containers/hosts/VMs (take your pick).  And you'd be even more in trouble when it spins it down due to inactivity.

Anything you want to be persisted between calls has to be sent to non-function storage, like a database.

**Comment by JunyiYi** [comment]
Close the issue since we have explained the behavior.
