### ISSUE TITLE
Event Grid trigger support

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-java-worker#58]
Java should support Event Grid now that Event Grid is GA.

**Comment by kevinhillinger** [comment]
This is now [in the source](https://github.com/Azure/azure-functions-java-worker/blob/dev/azure-functions-java-core/src/main/java/com/microsoft/azure/serverless/functions/annotation/EventGridTrigger.java). I believe this issue can be closed.

**Comment by JunyiYi** [comment]
Annotation is published, but the tooling has not been updated. @pragnagopa , you can close this as soon as the functions extension tooling is published.

**Comment by paulbatum** [comment]
This issue should have been closed once the change was committed. I'll let @pragnagopa comment on whether this is actually released or not yet.
