### ISSUE TITLE
Application insights agent will be part of the java worker

### ISSUE THREAD

**Issue by shreyas-gopalakrishna** [Azure/azure-functions-java-worker#585]
# [Draft Issue - This is not yet released]

- Application insights agent will be part of the java worker and included in worker release
- Java consumption, dedicated and Elastic premium apps 
  - Use `APPLICATIONINSIGHTS_ENABLE_AGENT` = true/false to enable and disable application insights
- Java consumption apps 
  - Application insights agent will start with the java process by default
  - To disable the agent from starting with java worker process use appsetting `languageWorkers:java:arguments` = `-DaiAgentOptOut`
     Please not this will increase cold start times.

**Comment by purijatin** [comment]
Would the behavior remain the same when deployed via docker image?

Currently, the documentation isn't clear when it comes to the docker image. This is what we are currently doing: https://stackoverflow.com/questions/71085054/java-azure-application-insights-dynamic-tracing-not-working-with-docker-images/71085468#71085468

And it is painful.
