### ISSUE TITLE
Enable asynchronous function execution flow.

### ISSUE THREAD

**Issue by Clockwork-Muse** [Azure/azure-functions-java-worker#60]
The recommendation for Azure functions is [to be asynchronous](https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices#use-async-code-but-avoid-blocking-calls) (granted, in context they're clearly expecting C# given the method names), however this is not a _language feature_ in Java.  Currently, the entry and exit points for Azure Java functions must be synchronous (although I'm assuming they execute in an async context externally).

In Java, this is mostly done via libraries.  In particular:
 - Returning, say, [`CompletableFuture<T>`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) (for some supported types, like `HttpResponseMessage`) should "just work".  Currently this returns: 
```json 
{
    "completedExceptionally": false,
    "numberOfDependents": 0,
    "cancelled": false,
    "done": true
}
```
 - Starting from version 9 Java includes the [`Flow` API](https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/Flow.html).  While this particular inclusion is new, this came in response to most of the major libraries that provide reactive/async capabilities in Java, meaning including it would enable consumers to use things like Akka or Reactor in their function.  Functions using this capability would probably be expected to take a `Publisher` and return a `Subscriber` - that is, the functions would really be acting as a _factory_, not as an invocation per se.

The Flow API in particular is likely to be helpful in Azure managing resource limits and scale-out, via the inclusion of back-pressure in the system.

**Comment by JunyiYi** [comment]
We need to decide which interface to use, Future<T> or CompletableFuture<T>.

**Comment by brunoborges** [comment]
@JonathanGiles  FYI

**Comment by Clockwork-Muse** [comment]
....well, if the ability to use gRPC is ever exposed more directly, would it make more sense to take and return flow types?  

Hmm, generally I feel like most HTTP calls are going to be one shots (in that many callers would call once, then go away), but things like queues and events, coming from a single source, are more likely to be kept open, where it would probably be more usual.

**Comment by smil2k** [comment]
> We need to decide which interface to use, `Future<T>` or `CompletableFuture<T>`.

Both can be supported easily:
- Can check for CompletableFuture with instanceof (and then .thenApply() can be used)
- Some libraries still return vanilla Future so it would make sense to support those. (executor/http thread needs to be blocked)

Additionally there can be two styles:

Future<HttpResponse> handler(...)

or

void handler(..., CompletableFuture<HttpResponse> res) {
}
... some thread somewhere ...
    res.complete(response);
...

**Comment by pragnagopa** [comment]
Tracking issue #244
