### ISSUE TITLE
Azure.azure-functions-java-worker pipeline fails to complete in 1 hour

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-java-worker#647]
In the integration test infrastructure, we have a 1 hour timeout for a pipeline execution. If the pipeline does not complete within this time, the job is marked as failed. Could you please let me know if this is the expected behavior (for the build to take longer than 1 hour)? Please note that this started to occurred after enabling Java 17. 

Here a couple of the failed builds:
https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=94780&view=results
https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=94755&view=results

**Comment by kaibocai** [comment]
Hi Francisco, thanks for reaching out. 
After we add the linux plantform https://github.com/Azure/azure-functions-java-worker/issues/441 and java17, now in total there are 2 (windows/linux) * 3 (java8/11/17) = 6 jobs to run. I found each job takes average time around 5 to 7 mins. But the waiting time between each jobs takes average around 5 to 10 mins. So the total build time can take up to 1 to 1 and half hours. 

Wondering if we should somehow parallelize the jobs.

**Comment by kaibocai** [comment]
parallelize the jobs will not be possible as it will cause race condition on the resources.

**Comment by Francisco-Gamino** [comment]
Thank you @kaibocai for the follow up. I will increase the timeout in for the pipeline execution script. I have a couple of follow up questions:

- What is the expected runtime of your pipeline? 
- When you enable a new version of Java, are you going to add it to the existing pipeline? I am asking this because if this is the case, then we will potentially run into this same issue again.

**Comment by kaibocai** [comment]
> Thank you @kaibocai for the follow up. I will increase the timeout in for the pipeline execution script. I have a couple of follow up questions:
> 
> * What is the expected runtime of your pipeline?
> * When you enable a new version of Java, are you going to add it to the existing pipeline? I am asking this because if this is the case, then we will potentially run into this same issue again.

Thank you Francisco. 

- For the expected run time: if ideally there is no waiting time between jobs, it should be around 40mins. But since the waiting can take up to 5-7 mins between each job, it's safe to expect it to finish in 1 and half hour. 
- Yes, that's correct. We are working on setting up a second copy of resources and parallelize jobs across the two copies of resources to reduce the pipeline running time.
