### ISSUE TITLE
function.json missing "dataType" property in some cases

### ISSUE THREAD

**Issue by satvu** [Azure/azure-functions-java-worker#680]
#### Repro steps

1. Create an EventHubs Trigger with `Cardinality.MANY` and an input parameter type of `String[]`.
2. Build the app.
3. Inspect `function.json` file.

#### Expected behavior

`function.json` file should have a line specifying the dataType. Example:

```
{
  "scriptFile" : "../someApp-1.0-SNAPSHOT.jar",
  "entryPoint" : "com.function.test.Function.someFunction",
  "bindings" : [ {
    "type" : "eventHubTrigger",
    "direction" : "in",
    "name" : "ehtrigger",
    "connection" : "EventHubConnectionAppSetting",
    "eventHubName" : "eventHubName",
    "cardinality" : "MANY",
    "dataType": "string"
  } ]
}
```

This host expects the dataType to be specified as "string" in this scenario, and from local testing, both dotnet-isolated and node exhibit this behavior. 

#### Actual behavior

`function.json` is missing the "dataType" property.

#### Known workarounds

After building the Java Function App, manually edit function.json to include the correct DataType expected.

ex. `"dataType": "string"`, `"dataType": "binary"`

#### Related information 

Related [test suite](https://github.com/Azure/azure-functions-dotnet-worker/blob/830d35ca4cbfee86ea367c07a3db08066d3162bd/test/FunctionMetadataGeneratorTests/FunctionMetadataGeneratorTests.cs#L464) from the dotnet-isolated worker. This should help in validating which dataType should be specified in a `function.json` file given a specific input type.

This additional property changes some behavior on the host side (we process messages as JObjects instead without this property), but unclear on how this changes the user experience. I think it will vary with different user scenarios, and we will want to fix it in case this results in inconsistent/unexpected behavior.

**Comment by kaibocai** [comment]
I am referring to host wiki on the function.json file at https://github.com/Azure/azure-functions-host/wiki/function.json and it state the JSON schema at http://json.schemastore.org/function, in which the `eventHubBinding` didn't include a `dataType` field. 
Also this could potentially be a break change for java customer, so need carefully tests. 
We haven't get any customer complaining about this issue yet, so will temporally close this one and reopen it once we get feedback from customer. Thanks.

**Comment by kaibocai** [comment]
Sorry I was wrong in above comments, I checked the source code again and I notice we do all customer to specify `dataType` in plenty of triggers/bindings annotation, take `EventHubTrigger` as an example we allow customer to define their dataType as a field of the annotation https://github.com/Azure/azure-functions-java-library/blob/2387b6b1d8d114c919377a6ac66f9fe63f4d31cd/src/main/java/com/microsoft/azure/functions/annotation/EventHubTrigger.java#L56, so customer will take the response to define correct type for their triggers/bindings
