### ISSUE TITLE
Warmup trigger is not working

### ISSUE THREAD

**Issue by leninalive** [Azure/azure-functions-java-worker#688]
Hello!

I am trying to setup very simple Warmup function (taken from appropriate example as is) along with Spring Cloud Function application, however, getting an exception during each invocation:

```
Result: Failure Exception: ClassCastException: class com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource cannot be cast to class java.lang.String (com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

Stack: java.lang.ClassCastException: class com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource cannot be cast to class java.lang.String (com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap') 
    at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:99) 
    at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56) 
    at com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource.computeByType(ExecutionContextDataSource.java:20) 
    at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByType(BindingDataStore.java:71) 
    at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:50) 
    at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolveArguments(ParameterResolver.java:22) 
    at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:20) at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19) 
    at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21) 
    at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:80) 
    at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:37)
    at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:12) 
    at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44) 
    at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:93) 
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) 
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) 
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) 
    at java.base/java.lang.Thread.run(Thread.java:833)
```

#### Investigative information

Please provide the following:

- Timestamp: 2022-12-13 20:25:10.488
- Invocation ID: 75f0ebdf-222f-48e0-acb0-fcc43a72dc3c
- Region: East US 2

#### Related information 

Source code I'm trying:

<details>
<summary>Source</summary>

```java
package com.example;

import com.microsoft.azure.functions.ExecutionContext;
import com.microsoft.azure.functions.annotation.FunctionName;
import com.microsoft.azure.functions.annotation.WarmupTrigger;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;

@Slf4j
@SpringBootApplication
@EnableFeignClients
public class ExampleApplication {

    public static void main(String[] args) {
        SpringApplication.run(ExampleApplication.class, args);
    }

    @FunctionName("Warmup")
    public void warmup(@WarmupTrigger Object warmupContext, ExecutionContext context) {
        context.getLogger().info("Function App instance is warm 🌞🌞🌞");
    }
}
```
</details>

**Comment by kaibocai** [comment]
Hey @leninalive , can you please share your function code? Here is the doc that contains an correct example of warmup trigger: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-warmup?tabs=in-process&pivots=programming-language-java#example

**Comment by leninalive** [comment]
> Hey @leninalive , can you please share your function code? Here is the doc that contains an correct example of warmup trigger: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-warmup?tabs=in-process&pivots=programming-language-java#example

Hello @kaibocai, I have attached it in 'Related Information', just expand Source spoiler. And yes, I ve got it from exactly that documentation page you linked.

**Comment by kaibocai** [comment]
I see, I don't think is the right way to code spring cloud function on azure, here is example how you can utilize spring cloud functions https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure. You need to use `FunctionInvoker` I believe.

**Comment by leninalive** [comment]
@kaibocai initially I was using FunctionInvoker, with same result. Just reduced to this variant to share it easily.

**Comment by kaibocai** [comment]
I see, thanks for reporting the issue. I will looking into it and try it out on my local. It will be great if you can share your original code with using `FunctionInvoker`, thanks. 

Also did you try a normal warmup trigger without using spring, does it also gives the same issue. If yes can you let me know if you are using maven function plugin or gradle and what version you are use. Thanks. 

It will be great if you can paste an picture of your lib folder you can found it in a smiliar path as below 
![image](https://user-images.githubusercontent.com/89094811/207441897-acb95217-f870-4f25-8d43-ac8332329b9a.png)

**Comment by leninalive** [comment]
Sure, handler:

```java
package com.example.handler;

import com.microsoft.azure.functions.ExecutionContext;
import com.microsoft.azure.functions.annotation.WarmupTrigger;
import org.springframework.cloud.function.adapter.azure.FunctionInvoker;

public class WarmupHandler extends FunctionInvoker<Object, Object> {

    @FunctionName("warmup")
    public void execute(
            @WarmupTrigger Object warmupContext,
            final ExecutionContext context) {
        context.getLogger().warning("Warmup trigger called");
        handleRequest(warmupContext, context);
    }
}
```

Function itself:

```java
package com.example.function;

import java.util.function.Function;

import com.microsoft.azure.functions.ExecutionContext;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Mono;

@Component
public class Warmup implements Function<Mono<Message<Object>>, Mono<Object>> {

    @Override
    public Mono<Object> apply(Mono<Message<Object>> mono) {
        return mono.map(input -> {
            ExecutionContext context = input.getHeaders().get("executionContext", ExecutionContext.class);
            context.getLogger().info("Warmed up executor");
            return input.getPayload();
        });
    }
}
```

I was hopeful that this approach will allow me to load Spring context during the warmup - that's why I was **not** trying without Spring. Meanwhile I am using Gradle and corresponding plugin, version is 1.11.0.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/16370118/207442905-42203d14-f012-41e8-b25c-cd6f2e1a50a3.png">
<img width="419" alt="image" src="https://user-images.githubusercontent.com/16370118/207443044-f36df335-067d-492a-810c-c2412f646d95.png">
<img width="362" alt="image" src="https://user-images.githubusercontent.com/16370118/207443127-0e617035-55a8-4988-8aeb-bab939d88662.png">

**Comment by kaibocai** [comment]
Can you use gradle plugin 1.11.1, it should fix the issue you have. Thanks.

**Comment by leninalive** [comment]
Hello, yes, somehow it helped.

**Comment by leninalive** [comment]
@kaibocai meanwhile I am seeing a lot of debug messages in Application Insights after probably your invasion. Tried to make them silent via host.json without any success:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/16370118/207566479-0980f0f3-288e-4d26-815f-07ef1c372ba0.png">

**Comment by kaibocai** [comment]
are you seeing debug message from spring? If yes tried to config logback.xml to disable them as spring cloud function are using logback as their log framework. thanks.

**Comment by kaibocai** [comment]
If you still have issue of the logs, please open anther issue. Will mark this warmup trigger issue as closed. thanks.
