### ISSUE TITLE
Should HTTP methods be an enum

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-functions-java-worker#74]
Rather than have the user dealing with Strings for GET, POST, etc, should there be an enum of all possible types? This would improve code readability and type inferencing for developers.

**Comment by JonathanGiles** [comment]
If this is to be introduced, I would think it makes sense to do this before the 1.0.0 release is made? Is this what you are thinking also?

**Comment by JunyiYi** [comment]
Since we only have limited engineer resources, and this is a low priority feature request. We may update it after the //Build event.

**Comment by JonathanGiles** [comment]
But that will still be before the 1.0.0 stable release, correct?

**Comment by JunyiYi** [comment]
I think so.

**Comment by brunoborges** [comment]
PR #112 adds enums for HTTP methods.

**Comment by asavaritayal** [comment]
Closing as this seems to be merged.
