### ISSUE TITLE
Investigate Java language worker integration test failures in Functions v4 for 10/18/23

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-java-worker#743]
Investigate Java language worker integration tests failures in Functions v4 for 10/18/23.

Here is the link to the pipeline executions with the test failures:
https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=156333&view=ms.vss-test-web.build-test-results-tab

<img width="835" alt="image" src="https://github.com/Azure/azure-functions-java-worker/assets/12720858/ee8248d1-ac33-4850-9f7c-41abe52d5c0f">

**Comment by kaibocai** [comment]
Hi @Francisco-Gamino , I added a new test for appinsight java agent, and I think it's causing the issue here. Please just ignore those errors for now. I will work on the fix soon.

**Comment by kaibocai** [comment]
Hi @Francisco-Gamino , the issue is resolved.  Plese find https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=156423&view=results
