### ISSUE TITLE
HttpTrigger webHookType should be an enum?

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-functions-java-worker#75]
It appears that there are only three valid values for the webHookType on HttpTrigger: genericJson, github, and slack (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#trigger---configuration). If this is the case, and if it is not possible for developers to augment this with additional functionality, it seems wise to instead provide an enum rather than use a String argument?

**Comment by JunyiYi** [comment]
@pragnagopa , are you able to confirm that only these options are available for HttpTrigger webhook?

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-functions-host#2563

**Comment by JonathanGiles** [comment]
So just to clarify - if the function.json schema is updated to use an enum instead of string, there is still a need in this azure-functions-java-worker project to update the API as well? If so, should this issue remain open until Azure/azure-functions-host#2563 is marked as resolved, so that we can track the update to this API? 

Also, it would be most beneficial to do this with some urgency, so that the API is correct for the 1.0.0 release of Azure Functions for Java, if at all possible.

**Comment by pragnagopa** [comment]
If we do decide to move an enum, I will co-ordinate any changes that are needed to be made on the language workers.

**Comment by JonathanGiles** [comment]
Great! My concern is just that I would love to see this in the 1.0.0 for Java, rather than breaking the API shortly after 1.0.0 is released and breaking all of our users. Anything that can be done to get this done before 1.0.0 would lead to a big win for Java users.
