### ISSUE TITLE
[Integration testing] Java language worker build pipeline has been failing since 1/31/24

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-java-worker#752]
The Java language worker pipeline has been failing since 1/31/24. Could you please investigate and resolve this issue? For more information, please see [Azure.azure-functions-java-worker](https://azfunc.visualstudio.com/Azure%20Functions/_build?definitionId=20). We need this fix for integration testing of the Functions Host and Core Tools.

**Comment by YunchuWang** [comment]
pipeline passes recently
