### ISSUE TITLE
Forward logging of dependencies (Feature Request)

### ISSUE THREAD

**Issue by nicenemo** [Azure/azure-functions-java-worker#90]
@JunyiYi  in a  comment at https://github.com/Azure/azure-functions-java-worker/issues/85

>  3rd party logging infrastructure, only console messages will be forwarded (actually pulled by the host). In contrast, the logger in ExecutionContext will send a message to the host (push to the host).

This means all logging of libraries that use the standard java.util.logging infrastructure will be send to */dev/null* or if the default console handler is used it will work more or less.

I think it would be useful to :
* send this logging to the host too
* configure per logger name what gets send to the host by setting the log level
   e.g.:
  *  a setting `(com.microsoft.jdbc.* , FINEST)`  will log data from level FINE to all logger with a name starting with `com.microsoft.jdbc` 
  *  a setting `(com.microsoft.jdbc.internal.DriverX, OFF)` will  not log data from all loggers named `com.microsoft.jdbc.internal.DriverX`  
 * should the default be `OFF` or `INFO`?

**Comment by JunyiYi** [comment]
This requires a detailed planning, and should be at P3 (a nice to have feature). It doesn't block any scenarios by design.

**Comment by kaibocai** [comment]
Azure function java support distributed tracing by now. It will instrument all popular log frameworks and libraries, it also allows you generate your owning trace, logs and metrics. You can find more details at https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions.
