### ISSUE TITLE
GRPC message length should be taken in and set as input parameter

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-java-worker#93]
Set send max send and receive message sizes on java client. Currently broken without fix because of following error:

`[SEVERE] {Application.parseCommandLine}: org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --grpcMaxMessageLength`

**Comment by pragnagopa** [comment]
Fixed in Commit # [e6c21f8c0d825fd7397d84e42fecd911a14061b1](https://github.com/Azure/azure-functions-java-worker/commit/e6c21f8c0d825fd7397d84e42fecd911a14061b1)
