### ISSUE TITLE
Update readme with build instructions

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#95]
Build instructions need to be udpated to include:
- Version of JDK
- Clear instructions using any IDE
- How to build proto file

**Comment by JunyiYi** [comment]
@pragnagopa , those information are put into the [devdoc](https://github.com/Azure/azure-functions-java-worker/blob/dev/azure-functions-java-worker/devdoc.md).

**Comment by JunyiYi** [comment]
Close this issue since the instructions have already been added.
