### ISSUE TITLE
Error "Unable to configure java worker. Could not find JAVA_HOME app setting." in the C# Azure Function v2

### ISSUE THREAD

**Issue by m-demydiuk** [Azure/azure-functions-java-worker#97]
Hi!

I started to create Azure Function v2 in Visual Studio 2017, language C#. And I got next errors in the console: 
"Unable to configure java worker. Could not find JAVA_HOME app setting."
"Could not configure language worker Java."

To get rid of this error I added JAVA_HOME to system variables and restarted computer. The error has gone. If I remove JAVA_HOME from system variables, it appears again.

Also, I noticed that azure function works with this error in the console. So this red error doesn't break function on the local machine. But I am afraid it may cause any problems in other environments.

Before we go live, we need to know, why this error occurs. We do not use java worker, we do not use durable functions lib and also we do not use Java in this project. So why this occurs?

Please advice us if you can, because for now it may block us.

**Comment by JunyiYi** [comment]
Track it in the correct place: https://github.com/Azure/azure-functions-host/issues/2765
